var TEXT_GAMEOVER  = "CONGRATULATION! YOU WON!";
var TEXT_LOSE = "SORRY, THE PLAYER %s WON THIS GAME";
var TEXT_SCORE     = "YOUR SCORE";
var TEXT_RESTART   = "RESTART";
var TEXT_SELECT_PLAYERS = "SELECT THE NUMBER OF PLAYERS!";
var TEXT_SELECT_COLOR = "SELECT A COLOR";

var TEXT_HELP_VALUE = "VALUE: %s";
var TEXT_HELP_VALUE_PTS = "VALUE: +%s pts";
var TEXT_DIGIT_VALUE = "DIGIT ON THE CARD";
var TEXT_UNO_RULE_VALUE = "REMEMBER TO CLICK IT ALSO FOR YOUR OPPONENTS!";
var TEXT_WELCOME = "WELCOME TO FOUR COLORS!";
var TEXT_ACTION_CARD = "ACTION CARD";
var TEXT_SKIP_CARD = "SKIP CARD";
var TEXT_REVERSE_CARD = "REVERSE CARD";
var TEXT_WILD_CARD = "WILD CARD";
var TEXT_WILD_THREE_CARD = "WILD DRAW THREE";
var TEXT_UNO_RULE = "1 RULE";
var TEXT_SKIP = "SKIP";

var TEXT_TUTORIAL1 = "MATCH CARDS BY COLOR OR NUMBER AND BE THE FIRST TO GET RID OF THEM!\n\nTHE WINNER'S SCORE WILL BE THE SAME AS THE VALUE OF OTHER PLAYERS CARDS. REACH %s PTS TO WIN THE GAME!";
var TEXT_TUTORIAL2 = "ACTION CARDS WILL MIX THE GAME UP!\n\nDRAW TWO FORCES THE NEXT PLAYER TO PICK TWO CARDS AND FORFEIT THE TURN";
var TEXT_TUTORIAL3 = "SKIP CARD STOPS THE NEXT PLAYER";
var TEXT_TUTORIAL4 = "REVERSE CARD SWITCHES THE GAME WISE";
var TEXT_TUTORIAL5 = "THE WILD CARD CAN BE PLACED ON ANY CARD AT ANY TIME AND ALLOWS YOU TO CHANGE THE COLOR TO PLAY";
var TEXT_TUTORIAL6 = "THE WILD DRAW THREE IS A SPECIAL WILD THAT ALLOWS YOU TO CHANGE THE COLOR AND FORCES THE NEXT PLAYER TO PICK 3 CARDS. TO USE THIS CARD YOU MUST HAVE NO OTHER ALTERNATIVE CARDS TO PLAY";
var TEXT_TUTORIAL7 = "DO NOT FORGET TO PRESS THE ' 1 ' BUTTON WHEN YOU'LL HAVE ONLY ONE CARD LEFT.\n\nIF YOU DON’T PRESS IT AND AN OPPONENT NOTICES, YOU WILL RECEIVE %s PENALTY CARDS.";

var TEXT_PLAYER_1 = "PLAYER 1";
var TEXT_PLAYER_2 = "PLAYER 2";
var TEXT_PLAYER_3 = "PLAYER 3";
var TEXT_PLAYER_4 = "PLAYER 4";
var TEXT_ALERT_1 = "%s CLICKED ' 1 ' FOR YOU... \n\nTAKE %s PENALTY CARDS";
var TEXT_ALERT_2 = "%s RECEIVED %s PENALTY CARDS FOR NOT CLICKING ' 1 '";
var TEXT_ALERT_3 = "YOU DIDN’T PRESS ' 1 ' BUT NO ONE NOTICED. \n\nYOU’RE SAFE, FOR NOW...";

var TEXT_SUMMARY = "SUMMARY";
var TEXT_PTS_TO_WINNER = "%s pts to winner";
var TEXT_WINNER = "WINNER! \n +%s pts";
var TEXT_PLAYER_WON ="%s WON THE GAME!";

var TEXT_MULTIPLAYER = "MULTIPLAYER";
var TEXT_MULTIPLAYER_EXPL = "PLAY ONLINE";
var TEXT_TRAINING = "TRAINING";
var TEXT_TRAINING_EXPL = "PLAY AGAINST AI";




function refreshLanguage(){
		if(s_iCurLang === LANG_AR){
			s_oCanvas.setAttribute('dir','rtl');
		}else{
			s_oCanvas.setAttribute('dir','ltr');
		}
	
		refreshLanguage_multiplayer();
	
        switch(s_iCurLang){
         case LANG_EN:{
				TEXT_GAMEOVER  = "CONGRATULATION! YOU WON!";
				TEXT_LOSE = "SORRY, THE PLAYER %s WON THIS GAME";
				TEXT_SCORE     = "YOUR SCORE";
				TEXT_RESTART   = "RESTART";
				TEXT_SELECT_PLAYERS = "SELECT THE NUMBER OF PLAYERS!";
				TEXT_SELECT_COLOR = "SELECT A COLOR";
				
				TEXT_HELP_VALUE = "VALUE: %s";
				TEXT_HELP_VALUE_PTS = "VALUE: +%s pts";
				TEXT_DIGIT_VALUE = "DIGIT ON THE CARD";
				TEXT_UNO_RULE_VALUE = "REMEMBER TO CLICK IT ALSO FOR YOUR OPPONENTS!";
				TEXT_WELCOME = "WELCOME TO FOUR COLORS!";
				TEXT_ACTION_CARD = "ACTION CARD";
				TEXT_SKIP_CARD = "SKIP CARD";
				TEXT_REVERSE_CARD = "REVERSE CARD";
				TEXT_WILD_CARD = "WILD CARD";
				TEXT_WILD_THREE_CARD = "WILD DRAW THREE";
				TEXT_UNO_RULE = "1 RULE";
				TEXT_SKIP = "SKIP";

				TEXT_TUTORIAL1 = "MATCH CARDS BY COLOR OR NUMBER AND BE THE FIRST TO GET RID OF THEM!\n\nTHE WINNER'S SCORE WILL BE THE SAME AS THE VALUE OF OTHER PLAYERS CARDS. REACH %s PTS TO WIN THE GAME!";
				TEXT_TUTORIAL2 = "ACTION CARDS WILL MIX THE GAME UP!\n\nDRAW TWO FORCES THE NEXT PLAYER TO PICK TWO CARDS AND FORFEIT THE TURN";
				TEXT_TUTORIAL3 = "SKIP CARD STOPS THE NEXT PLAYER";
				TEXT_TUTORIAL4 = "REVERSE CARD SWITCHES THE GAME WISE";
				TEXT_TUTORIAL5 = "THE WILD CARD CAN BE PLACED ON ANY CARD AT ANY TIME AND ALLOWS YOU TO CHANGE THE COLOR TO PLAY";
				TEXT_TUTORIAL6 = "THE WILD DRAW THREE IS A SPECIAL WILD THAT ALLOWS YOU TO CHANGE THE COLOR AND FORCES THE NEXT PLAYER TO PICK 3 CARDS. TO USE THIS CARD YOU MUST HAVE NO OTHER ALTERNATIVE CARDS TO PLAY";
				TEXT_TUTORIAL7 = "DO NOT FORGET TO PRESS THE ' 1 ' BUTTON WHEN YOU'LL HAVE ONLY ONE CARD LEFT.\n\nIF YOU DON’T PRESS IT AND AN OPPONENT NOTICES, YOU WILL RECEIVE %s PENALTY CARDS.";
				
				TEXT_PLAYER_1 = "PLAYER 1";
				TEXT_PLAYER_2 = "PLAYER 2";
				TEXT_PLAYER_3 = "PLAYER 3";
				TEXT_PLAYER_4 = "PLAYER 4";
				TEXT_ALERT_1 = "%s CLICKED ' 1 ' FOR YOU... \n\nTAKE %s PENALTY CARDS";
				TEXT_ALERT_2 = "%s RECEIVED %s PENALTY CARDS FOR NOT CLICKING ' 1 '";
				TEXT_ALERT_3 = "YOU DIDN’T PRESS ' 1 ' BUT NO ONE NOTICED. \n\nYOU’RE SAFE, FOR NOW...";

				TEXT_SUMMARY = "SUMMARY";
				TEXT_PTS_TO_WINNER = "%s pts to winner";
				TEXT_WINNER = "WINNER! \n +%s pts";
				TEXT_PLAYER_WON ="%s WON THE GAME!";
					
				TEXT_MULTIPLAYER = "MULTIPLAYER";
				TEXT_MULTIPLAYER_EXPL = "PLAY ONLINE";
				TEXT_TRAINING = "TRAINING";
				TEXT_TRAINING_EXPL = "PLAY AGAINST AI";

			break;
		 }
		 case LANG_RU:{
				TEXT_GAMEOVER  = "ПОЗДРАВЛЯЕМ! ВЫ ВЫИГРАЛИ!";
				TEXT_LOSE = "СОЖАЛЕЕМ, ИГРОК %s ПОБЕЖДАЕТ";
				TEXT_SCORE     = "ВАШ СЧЕТ";
				TEXT_RESTART   = "ЗАНОВО";
				TEXT_SELECT_PLAYERS = "ВЫБЕРИТЕ КОЛИЧЕСТВО ИГРОКОВ";
				TEXT_SELECT_COLOR = "ВЫБЕРИТЕ ЦВЕТ ";
				
				TEXT_HELP_VALUE = "ЗНАЧЕНИЕ: %s";
				TEXT_HELP_VALUE_PTS = "ЗНАЧЕНИЕ: +%s очк.";
				TEXT_DIGIT_VALUE = "ЦИФРА НА КАРТЕ";
				TEXT_UNO_RULE_VALUE = "НЕ ЗАБУДЬ НАЖАТЬ И ЗА СВОИХ СОПЕРНИКОВ!";
				TEXT_WELCOME = "ДОБРО ПОЖАЛОВАТЬ В FOUR COLORS!";
				TEXT_ACTION_CARD = "КАРТА ДЕЙСТВИЯ";
				TEXT_SKIP_CARD = "КАРТА ПРОПУСК";
				TEXT_REVERSE_CARD = "КАРТА РАЗВОРОТ";
				TEXT_WILD_CARD = "КАРТА-ДЖОКЕР";
				TEXT_WILD_THREE_CARD = "ДЖОКЕР +3";
				TEXT_UNO_RULE = "1 ПРАВИЛО";
				TEXT_SKIP = "ПРОПУСТИТЬ";

				TEXT_TUTORIAL1 = "СБРАСЫВАЙТЕ ОДИНАКОВЫЕ ПО ЦВЕТУ ИЛИ ДОСТОИНСТВУ КАРТЫ.\n\nСЧЕТ ПОБЕДИТЕЛЯ БУДЕТ РАВЕН ЦЕННОСТИ КАРТ ДРУГИХ ИГРОКОВ. НАБЕРИТЕ %s ОЧКОВ, ЧТОБЫ ВЫИГРАТЬ!";
				TEXT_TUTORIAL2 = "ОСОБЫЕ КАРТЫ НЕ ДАДУТ ЗАСКУЧАТЬ!\n\n«ТЯНИ ДВЕ» — СЛЕДУЮЩЕМУ ИГРОКУ ПРИДЕТСЯ ВЫТАЩИТЬ ДВЕ КАРТЫ И ПРОПУСТИТЬ ХОД.";
				TEXT_TUTORIAL3 = "«ПРОПУСК» — ПРОТИВНИК ЛИШАЕТСЯ ХОДА.";
				TEXT_TUTORIAL4 = "«ХОД ОБРАТНО» МЕНЯЕТ ОЧЕРЕДНОСТЬ ХОДА ИГРОКОВ.";
				TEXT_TUTORIAL5 = "«ВЫБОР ЦВЕТА» МОЖНО ПОЛОЖИТЬ НА ЛЮБУЮ КАРТУ, ЧТОБЫ СМЕНИТЬ ЦВЕТ.";
				TEXT_TUTORIAL6 = "«ТЯНИ 3» — ОСОБАЯ КАРТА. С НЕЙ ВЫ МОЖЕТЕ ПОМЕНЯТЬ ЦВЕТ, А СЛЕДУЮЩЕМУ ИГРОКУ ПРИДЕТСЯ ТЯНУТЬ 3 КАРТЫ. НО ИСПОЛЬЗОВАТЬ ЕЕ МОЖНО ТОЛЬКО ТОГДА, КОГДА У ВАС НЕТ ДРУГИХ ХОДОВ.";
				TEXT_TUTORIAL7 = "НЕ ЗАБУДЬ НАЖАТЬ КНОПКУ ' 1 ', КОГДА У ТЕБЯ ОСТАНЕТСЯ ВСЕГО ОДНА КАРТА.\n\nЕСЛИ ТЫ НЕ НАЖМЕШЬ И СОПЕРНИК ЭТО ЗАМЕТИТ, ТЫ ПОЛУЧИШЬ %s ШТРАФНЫХ КАРТ.";

				TEXT_PLAYER_1 = "ИГРОК 1";
				TEXT_PLAYER_2 = "ИГРОК 2";
				TEXT_PLAYER_3 = "ИГРОК 3";
				TEXT_PLAYER_4 = "ИГРОК 4";
				TEXT_ALERT_1 = "%s НАЖАЛ ' 1 ' ЗА ТЕБЯ... \n\nВОЗЬМИ %s ШТРАФНЫХ КАРТ";
				TEXT_ALERT_2 = "%s ПОЛУЧИЛ %s ШТРАФНЫХ КАРТ ЗА ТО, ЧТО НЕ НАЖАЛ ' 1 '";
				TEXT_ALERT_3 = "ТЫ НЕ НАЖАЛ ' 1 ', НО НИКТО НЕ ЗАМЕТИЛ. \n\nТЕБЕ ПОВЕЗЛО... ПОКА...";

				TEXT_SUMMARY = "ИТОГО";
				TEXT_PTS_TO_WINNER = "%s очк. за победу";
				TEXT_WINNER = "ПОБЕДИТЕЛЬ! \n +%s очк.";
				TEXT_PLAYER_WON ="%s ПОБЕЖДАЕТ В ИГРЕ!";

				TEXT_MULTIPLAYER = "МУЛЬТИПЛЕЕР";
				TEXT_MULTIPLAYER_EXPL = "ИГРАТЬ ОНЛАЙН";
				TEXT_TRAINING = "ТРЕНИРОВКА";
				TEXT_TRAINING_EXPL = "ИГРАТЬ ПРОТИВ AI";
					
				break;
		 }
		 case LANG_ES:{
				TEXT_GAMEOVER  = "¡ENHORABUENA! ¡HAS GANADO!";
				TEXT_LOSE = "LO SIENTO, EL JUGADOR %s HA GANADO ESTA PARTIDA";
				TEXT_SCORE     = "TU PUNTUACIÓN";
				TEXT_RESTART   = "REINICIAR";
				TEXT_SELECT_PLAYERS = "SELECCIONA EL NÚMERO DE JUGADORES";
				TEXT_SELECT_COLOR = "SELECCIONA UN COLOR";
				
				TEXT_HELP_VALUE = "VALOR: %s";
				TEXT_HELP_VALUE_PTS = "VALOR: +%s pts";
				TEXT_DIGIT_VALUE = "NÚMERO EN LA CARTA";
				TEXT_UNO_RULE_VALUE = "¡RECUERDA HACER CLIC TAMBIÉN POR TUS OPONENTES!";
				TEXT_WELCOME = "¡BIENVENIDO A FOUR COLORS!";
				TEXT_ACTION_CARD = "CARTA DE ACCIÓN";
				TEXT_SKIP_CARD = "CARTA SALTAR";
				TEXT_REVERSE_CARD = "CARTA REVERSA";
				TEXT_WILD_CARD = "CARTA COMODÍN";
				TEXT_WILD_THREE_CARD = "COMODÍN +3";
				TEXT_UNO_RULE = "1 REGLA";
				TEXT_SKIP = "SALTAR";

				TEXT_TUTORIAL1 = "COMBINA CARTAS POR COLOR O NÚMERO Y SÉ EL PRIMERO EN DESHACERTE DE ELLAS.\n\nLA PUNTUACIÓN DEL GANADOR SERÁ LA MISMA QUE EL VALOR DE LAS CARTAS DE LOS DEMÁS JUGADORES. ¡LLEGA A %s PUNTOS PARA GANAR LA PARTIDA!";
				TEXT_TUTORIAL2 = "¡LAS CARTAS DE ACCIÓN ALTERARÁN EL JUEGO!\n\nROBAR DOS OBLIGA AL SIGUIENTE JUGADOR A COGER DOS CARTAS Y PERDER EL TURNO";
				TEXT_TUTORIAL3 = "SALTAR CARTA DETIENE AL SIGUIENTE JUGADOR";
				TEXT_TUTORIAL4 = "LA CARTA INVERSA CAMBIA EL JUEGO";
				TEXT_TUTORIAL5 = "EL COMODÍN PUEDE COLOCARSE EN CUALQUIER CARTA EN CUALQUIER MOMENTO Y PERMITE CAMBIAR EL COLOR PARA JUGAR";
				TEXT_TUTORIAL6 = "EL COMODÍN 'ROBAR TRES' ES UN COMODÍN ESPECIAL QUE TE PERMITE CAMBIAR EL COLOR Y OBLIGA AL SIGUIENTE JUGADOR A ELEGIR 3 CARTAS. PARA USAR ESTA CARTA NO DEBES TENER OTRAS CARTAS ALTERNATIVAS PARA JUGAR";
				TEXT_TUTORIAL7 = "NO OLVIDES PULSAR EL BOTÓN ' 1 ' CUANDO TE QUEDE SOLO UNA CARTA.\n\nSI NO LO PULSAS Y UN OPONENTE SE DA CUENTA, RECIBIRÁS %s CARTAS DE PENALIZACIÓN.";

				TEXT_PLAYER_1 = "JUGADOR 1";
				TEXT_PLAYER_2 = "JUGADOR 2";
				TEXT_PLAYER_3 = "JUGADOR 3";
				TEXT_PLAYER_4 = "JUGADOR 4";
				TEXT_ALERT_1 = "%s HA PULSADO ' 1 ' POR TI... \n\nTOMA %s CARTAS DE PENALIZACIÓN";
				TEXT_ALERT_2 = "%s RECIBIÓ %s CARTAS DE PENALIZACIÓN POR NO PULSAR ' 1 '";
				TEXT_ALERT_3 = "NO PULSASTE ' 1 ' PERO NADIE SE DIO CUENTA. \n\nESTÁS A SALVO... POR AHORA...";

				TEXT_SUMMARY = "RESUMEN";
				TEXT_PTS_TO_WINNER = "%s puntos al ganador";
				TEXT_WINNER = "¡GANADOR! \n +%s pts";
				TEXT_PLAYER_WON ="¡%s HA GANADO LA PARTIDA!";

				TEXT_MULTIPLAYER = "MULTIJUGADOR";
				TEXT_MULTIPLAYER_EXPL = "JUGAR EN LÍNEA";
				TEXT_TRAINING = "ENTRENAMIENTO";
				TEXT_TRAINING_EXPL = "JUGAR CONTRA LA AI";
				
				break;
		 }
		 case LANG_FR:{
				TEXT_GAMEOVER  = "FÉLICITATIONS ! VOUS AVEZ GAGNÉ !";
				TEXT_LOSE = "DÉSOLÉ, LE JOUEUR %s A REMPORTÉ CETTE PARTIE";
				TEXT_SCORE     = "VOTRE SCORE";
				TEXT_RESTART   = "REDÉMARRER";
				TEXT_SELECT_PLAYERS = "SÉLECTIONNEZ LE NOMBRE DE JOUEURS !";
				TEXT_SELECT_COLOR = "SÉLECTIONNEZ UNE COULEUR";
				
				TEXT_HELP_VALUE = "VALEUR : %s";
				TEXT_HELP_VALUE_PTS = "VALEUR : +%s pts";
				TEXT_DIGIT_VALUE = "CHIFFRE SUR LA CARTE";
				TEXT_UNO_RULE_VALUE = "N’OUBLIE PAS DE CLIQUER AUSSI POUR TES ADVERSAIRES !";
				TEXT_WELCOME = "BIENVENUE DANS FOUR COLORS !";
				TEXT_ACTION_CARD = "CARTE D’ACTION";
				TEXT_SKIP_CARD = "CARTE PASSER";
				TEXT_REVERSE_CARD = "CARTE INVERSION";
				TEXT_WILD_CARD = "CARTE JOKER";
				TEXT_WILD_THREE_CARD = "JOKER +3";
				TEXT_UNO_RULE = "RÈGLE 1";
				TEXT_SKIP = "PASSER";
				
				TEXT_TUTORIAL1 = "ASSOCIEZ DES CARTES PAR COULEUR OU PAR NOMBRE ET SOYEZ LE PREMIER À VOUS EN DÉBARRASSER !\n\nLE SCORE DU GAGNANT SERA ÉQUIVALENT À LA VALEUR DES CARTES DES AUTRES JOUEURS. ATTEIGNEZ %s PTS AFIN DE REMPORTER LA PARTIE !";
				TEXT_TUTORIAL2 = "LES CARTES D’ACTION PERMETTENT DE VARIER LE JEU !\n\nTIRER DEUX CARTES OBLIGE LE JOUEUR SUIVANT À CHOISIR DEUX CARTES ET À RENONCER À SON TOUR";
				TEXT_TUTORIAL3 = "LA CARTE PASSER ARRÊTE LE JOUEUR SUIVANT";
				TEXT_TUTORIAL4 = "LA CARTE INVERSION CHANGE LE SENS DU JEU";
				TEXT_TUTORIAL5 = "LE JOKER PEUT ÊTRE PLACÉ À TOUT MOMENT SUR N’IMPORTE QUELLE CARTE ET VOUS PERMET DE MODIFIER LA COULEUR À JOUER";
				TEXT_TUTORIAL6 = "LE JOKER TIRER 3 EST UN JOKER SPÉCIAL QUI VOUS PERMET DE MODIFIER LA COULEUR ET OBLIGE LE JOUEUR SUIVANT À CHOISIR 3 CARTES. POUR POUVOIR UTILISER CETTE CARTE, VOUS NE DEVEZ PAS AVOIR D’AUTRES CARTES À JOUER";
				TEXT_TUTORIAL7 = "N’OUBLIE PAS D’APPUYER SUR LE BOUTON ' 1 ' QUAND IL NE TE RESTERA PLUS QU’UNE CARTE.\n\nSI TU N’APPUYES PAS ET QU’UN ADVERSAIRE LE REMARQUE, TU RECEVRAS %s CARTES DE PÉNALITÉ.";

				TEXT_PLAYER_1 = "JOUEUR 1";
				TEXT_PLAYER_2 = "JOUEUR 2";
				TEXT_PLAYER_3 = "JOUEUR 3";
				TEXT_PLAYER_4 = "JOUEUR 4";
				TEXT_ALERT_1 = "%s A CLIQUÉ SUR ' 1 ' À TA PLACE... \n\nPRENDS %s CARTES DE PÉNALITÉ";
				TEXT_ALERT_2 = "%s A REÇU %s CARTES DE PÉNALITÉ POUR NE PAS AVOIR CLIQUÉ SUR ' 1 '";
				TEXT_ALERT_3 = "TU N’AS PAS APPUYÉ SUR ' 1 ' MAIS PERSONNE NE L’A REMARQUÉ. \n\nTU ES SAUVÉ, POUR L’INSTANT...";

				TEXT_SUMMARY = "RÉSUMÉ";
				TEXT_PTS_TO_WINNER = "%s pts au vainqueur";
				TEXT_WINNER = "GAGNANT ! \n +%s pts";
				TEXT_PLAYER_WON ="%s A REMPORTÉ LA PARTIE !";

				TEXT_MULTIPLAYER = "MULTIJOUEUR";
				TEXT_MULTIPLAYER_EXPL = "JOUER EN LIGNE";
				TEXT_TRAINING = "ENTRAÎNEMENT";
				TEXT_TRAINING_EXPL = "JOUER CONTRE L'AI";
					
				break;
		 }
		 case LANG_DE:{
				TEXT_GAMEOVER  = "GLÜCKWUNSCH! SIE HABEN GEWONNEN!";
				TEXT_LOSE = "TUT UNS LEID, ABER DER SPIELER %sHAT DAS SPIEL GEWONNEN";
				TEXT_SCORE     = "IHRE PUNKTZAHL";
				TEXT_RESTART   = "NEU STARTEN";
				TEXT_SELECT_PLAYERS = "WÄHLEN SIE DIE ANZAHL DER SPIELER!";
				TEXT_SELECT_COLOR = "WÄHLEN SIE EINE FARBE";
				
				TEXT_HELP_VALUE = "WERT: %s";
				TEXT_HELP_VALUE_PTS = "WERT: +%s Pkt";
				TEXT_DIGIT_VALUE = "ZAHL AUF DER KARTE";
				TEXT_UNO_RULE_VALUE = "DENKE DARAN, AUCH FÜR DEINE GEGNER ZU KLICKEN!";
				TEXT_WELCOME = "WILLKOMMEN BEI FOUR COLORS!";
				TEXT_ACTION_CARD = "AKTIONSKARTE";
				TEXT_SKIP_CARD = "ÜBERSPRINGEN-KARTE";
				TEXT_REVERSE_CARD = "RICHTUNGSWECHSEL";
				TEXT_WILD_CARD = "JOKERKARTE";
				TEXT_WILD_THREE_CARD = "JOKER +3";
				TEXT_UNO_RULE = "1 REGEL";
				TEXT_SKIP = "ÜBERSPRINGEN";
				
				TEXT_TUTORIAL1 = "ORDNEN SIE DIE KARTEN NACH FARBE ODER ZAHL UND WERDE SIE ALS ERSTER LOS!\n\nDER GEWINNER ERHÄLT DIE GLEICHE PUNKTZAHL WIE DER WERT DER ANDEREN SPIELERKARTEN. ERREICHEN SIE %sPUNKTE, UM DAS SPIEL ZU GEWINNEN!";
				TEXT_TUTORIAL2 = "AKTIONSKARTEN MISCHEN DAS SPIEL AUF!\n\nWENN MAN ZWEI KARTEN ZIEHT, MUSS DER NÄCHSTE SPIELER ZWEI KARTEN ZIEHEN UND VERLIERT DEN ZUG";
				TEXT_TUTORIAL3 = "KARTE ÜBERSPRINGEN HÄLT DEN NÄCHSTEN SPIELER AN";
				TEXT_TUTORIAL4 = "UMGEKEHRTE KARTE WECHSELT DIE SPIELWEISE";
				TEXT_TUTORIAL5 = "DER JOKER KANN JEDERZEIT AUF EINE BELIEBIGE KARTE GELEGT WERDEN UND ERMÖGLICHT ES IHNEN, DIE FARBE ZU ÄNDERN, UM ZU SPIELEN";
				TEXT_TUTORIAL6 = "DER JOKER „DREI ZIEHEN“ IST EIN SPEZIELLER JOKER, MIT DEM SIE DIE FARBE ÄNDERN KÖNNEN UND DER DEN NÄCHSTEN SPIELER ZWINGT, 3 KARTEN ZU ZIEHEN. UM DIESE KARTE ZU BENUTZEN, DÜRFEN SIE KEINE ANDEREN KARTEN SPIELEN";
				TEXT_TUTORIAL7 = "VERGISSE NICHT, DEN ' 1 '-KNOPF ZU DRÜCKEN, WENN DU NUR NOCH EINE KARTE HAST.\n\nWENN DU NICHT DRÜCKST UND EIN GEGNER ES BEMERKT, BEKOMMST DU %s STRAFKARTEN.";

				TEXT_PLAYER_1 = "SPIELER 1";
				TEXT_PLAYER_2 = "SPIELER 2";
				TEXT_PLAYER_3 = "SPIELER 3";
				TEXT_PLAYER_4 = "SPIELER 4";
				TEXT_ALERT_1 = "%s HAT FÜR DICH AUF ' 1 ' GEKLICKT... \n\nNIMM %s STRAFKARTEN";
				TEXT_ALERT_2 = "%s HAT %s STRAFKARTEN ERHALTEN, WEIL ER NICHT AUF ' 1 ' GEKLICKT HAT";
				TEXT_ALERT_3 = "DU HAST NICHT AUF ' 1 ' GEDRÜCKT, ABER NIEMAND HAT ES BEMERKT. \n\nDU BIST VORERST SICHER...";

				TEXT_SUMMARY = "ZUSAMMENFASSUNG";
				TEXT_PTS_TO_WINNER = "%s Punkte für den Gewinner";
				TEXT_WINNER = "GEWINNER! \n +%s Pkt";
				TEXT_PLAYER_WON ="%sSIE HABEN DAS SPIEL GEWONNEN!";


				TEXT_MULTIPLAYER = "MEHRSPIELER";
				TEXT_MULTIPLAYER_EXPL = "ONLINE SPIELEN";
				TEXT_TRAINING = "TRAINING";
				TEXT_TRAINING_EXPL = "GEGEN DIE AI SPIELEN";
					
				break;
		 }
		 case LANG_PT:{
				TEXT_GAMEOVER  = "PARABÉNS! GANHASTE!";
				TEXT_LOSE = "DESCULPA, O JOGADOR %s GANHOU ESTE JOGO";
				TEXT_SCORE     = "A TUA PONTUAÇÃO";
				TEXT_RESTART   = "REINICIAR";
				TEXT_SELECT_PLAYERS = "SELECCIONA O NÚMERO DE JOGADORES";
				TEXT_SELECT_COLOR = "SELECCIONA UMA COR";
				
				TEXT_HELP_VALUE = "VALOR: %s";
				TEXT_HELP_VALUE_PTS = "VALOR: +%s pts";
				TEXT_DIGIT_VALUE = "NÚMERO NA CARTA";
				TEXT_UNO_RULE_VALUE = "LEMBRE-SE DE CLICAR TAMBÉM PELOS SEUS OPONENTES!";
				TEXT_WELCOME = "BEM-VINDO AO FOUR COLORS!";
				TEXT_ACTION_CARD = "CARTA DE AÇÃO";
				TEXT_SKIP_CARD = "CARTA PULAR";
				TEXT_REVERSE_CARD = "CARTA REVERTER";
				TEXT_WILD_CARD = "CARTA CURINGA";
				TEXT_WILD_THREE_CARD = "CURINGA +3";
				TEXT_UNO_RULE = "1 REGRA";
				TEXT_SKIP = "PULAR";

				TEXT_TUTORIAL1 = "COMBINA CARTAS POR COR OU NÚMERO E SÊ O PRIMEIRO A SE LIVRAR DELAS!\n\nA PONTUAÇÃO DO VENCEDOR SERÁ A MESMA QUE O VALOR DAS CARTAS DOS OUTROS JOGADORES. ALCANÇA %s PONTOS PARA GANHAR A PARTIDA!";
				TEXT_TUTORIAL2 = "CARTAS DE ACÇÃO VÃO REMEXER O JOGO!\n\nTIRAR DUAS FORÇA O JOGADOR SEGUINTE A ESCOLHER DUAS CARTAS E A PERDER A VEZ";
				TEXT_TUTORIAL3 = "SALTAR A CARTA PÁRA O JOGADOR SEGUINTE";
				TEXT_TUTORIAL4 = "INVERTER AS CARTAS MUDA O SENTIDO JOGO";
				TEXT_TUTORIAL5 = "O 'WILD CARD' PODE SER COLOCADA SOBRE QUALQUER CARTA EM QUALQUER ALTURA E PERMITE-TE MUDAR A COR A JOGAR";
				TEXT_TUTORIAL6 = "O WILD 'TIRA TRÊS' É UM WILD ESPECIAL QUE TE PERMITE MUDAR A COR E OBRIGA O JOGADOR SEGUINTE A ESCOLHER 3 CARTAS. PARA UTILIZAR ESTE CARTA NÃO PODES TER OUTRAS CARTAS ALTERNATIVAS PARA JOGAR";
				TEXT_TUTORIAL7 = "NÃO ESQUEÇA DE PRESSIONAR O BOTÃO ' 1 ' QUANDO TIVER APENAS UMA CARTA.\n\nSE NÃO PRESSIONAR E UM OPONENTE PERCEBER, VOCÊ RECEBERÁ %s CARTAS DE PENALIDADE.";

				TEXT_PLAYER_1 = "JOGADOR 1";
				TEXT_PLAYER_2 = "JOGADOR 2";
				TEXT_PLAYER_3 = "JOGADOR 3";
				TEXT_PLAYER_4 = "JOGADOR 4";
				TEXT_ALERT_1 = "%s CLICOU EM ' 1 ' POR VOCÊ... \n\nPEGUE %s CARTAS DE PENALIDADE";
				TEXT_ALERT_2 = "%s RECEBEU %s CARTAS DE PENALIDADE POR NÃO TER CLICADO EM ' 1 '";
				TEXT_ALERT_3 = "VOCÊ NÃO PRESSIONOU ' 1 ', MAS NINGUÉM PERCEBEU. \n\nESTÁ A SALVO, POR ENQUANTO...";

				TEXT_SUMMARY = "RESUMO";
				TEXT_PTS_TO_WINNER = "%s pontos para o vencedor";
				TEXT_WINNER = "VENCEDOR! \n +%s pts";
				TEXT_PLAYER_WON ="%s GANHOU O JOGO!";

				TEXT_MULTIPLAYER = "MULTIJOGADOR";
				TEXT_MULTIPLAYER_EXPL = "JOGAR ONLINE";
				TEXT_TRAINING = "TREINAMENTO";
				TEXT_TRAINING_EXPL = "JOGAR CONTRA A AI";
					
				break;
		 }
		 case LANG_IT:{
			 TEXT_GAMEOVER  = "CONGRATULAZIONI! HAI VINTO!";
				TEXT_LOSE = "IL GIOCATORE %s HA VINTO QUESTA PARTITA";
				TEXT_SCORE     = "IL TUO PUNTEGGIO";
				TEXT_RESTART   = "RIAVVIA";
				TEXT_SELECT_PLAYERS = "SELEZIONA IL NUMERO DI GIOCATORI!";
				TEXT_SELECT_COLOR = "SELEZIONA UN COLORE";
			
				TEXT_HELP_VALUE = "VALORE: %s";
				TEXT_HELP_VALUE_PTS = "VALORE: +%s pti";
				TEXT_DIGIT_VALUE = "NUMERO SULLA CARTA";
				TEXT_UNO_RULE_VALUE = "RICORDA DI CLICCARLO ANCHE PER I TUOI AVVERSARI!";
				TEXT_WELCOME = "BENVENUTO IN FOUR COLORS!";
				TEXT_ACTION_CARD = "CARTA AZIONE";
				TEXT_SKIP_CARD = "CARTA SALTA";
				TEXT_REVERSE_CARD = "CARTA INVERTI";
				TEXT_WILD_CARD = "CARTA JOLLY";
				TEXT_WILD_THREE_CARD = "JOLLY +3";
				TEXT_UNO_RULE = "REGOLA 1";
				TEXT_SKIP = "SALTA";
			
				TEXT_TUTORIAL1 = "ABBINA LE CARTE PER COLORE O NUMERO E DIVENTA IL PRIMO A LIBERARSI DEL MAZZO!\n\nIL PUNTEGGIO DEL VINCITORE SARÀ PARI AL VALORE DELLE CARTE DEGLI ALTRI GIOCATORI. RAGGIUNGI %s PUNTI PER VINCERE LA PARTITA!";
				TEXT_TUTORIAL2 = "LE CARTE AZIONE RENDERANNO CAOTICO IL GIOCO!\n\nPESCA DUE COSTRINGE IL GIOCATORE SUCCESSIVO A PESCARE DUE CARTE E PERDERE IL TURNO";
				TEXT_TUTORIAL3 = "LA CARTA SALTA FERMA IL GIOCATORE SUCCESSIVO";
				TEXT_TUTORIAL4 = "LA CARTA INVERTI CAMBIA IL SENSO DEL GIOCO";
				TEXT_TUTORIAL5 = "LE CARTE JOLLY POSSONO ESSERE POSIZIONATE SU QUALSIASI CARTA IN QUALSIASI MOMENTO E CONSENTONO DI CAMBIARE IL COLORE DI GIOCO";
				TEXT_TUTORIAL6 = "IL JOLLY PESCA TRE È UN JOLLY SPECIALE CHE TI PERMETTE DI CAMBIARE IL COLORE E COSTRINGE IL GIOCATORE SUCCESSIVO A PESCARE 3 CARTE. PER USARE QUESTA CARTA NON DEVI AVERE ALTRE CARTE ALTERNATIVE DA GIOCARE";
				TEXT_TUTORIAL7 = "NON DIMENTICARE DI PREMERE IL PULSANTE ' 1 ' QUANDO TI RESTERÀ SOLO UNA CARTA.\n\nSE NON LO PREMI E UN AVVERSARIO SE NE ACCORGE, RICEVERAI %s CARTE DI PENALITÀ.";

				TEXT_PLAYER_1 = "GIOCATORE 1";
				TEXT_PLAYER_2 = "GIOCATORE 2";
				TEXT_PLAYER_3 = "GIOCATORE 3";
				TEXT_PLAYER_4 = "GIOCATORE 4";
				TEXT_ALERT_1 = "%s HA CLICCATO ' 1 ' AL TUO POSTO... \n\nPRENDI %s CARTE DI PENALITA'";
				TEXT_ALERT_2 = "%s HA RICEVUTO %s CARTE DI PENALITA' PER NON AVER CLICCATO ' 1 ' ";
				TEXT_ALERT_3 = "NON HAI PREMUTO ' 1 ' MA NESSUNO SE NE E' ACCORTO. \n\nSEI SALVO, PER ORA...";

				TEXT_SUMMARY = "RIEPILOGO";
				TEXT_PTS_TO_WINNER = "%s pt al vincitore";
				TEXT_WINNER = "VINCITORE! \n +%s pt";
				TEXT_PLAYER_WON ="%s HA VINTO LA PARTITA!";

				TEXT_MULTIPLAYER = "MULTIGIOCATORE";
				TEXT_MULTIPLAYER_EXPL = "GIOCA ONLINE";
				TEXT_TRAINING = "ALLENAMENTO";
				TEXT_TRAINING_EXPL = "GIOCA CONTRO L'AI";
						
				break;
		 }
		 case LANG_TR:{
			 TEXT_GAMEOVER  = "TEBRİKLER! KAZANDIN!";
				TEXT_LOSE = "BU OYUNU %s KAZANDI";
				TEXT_SCORE     = "SKORUN";
				TEXT_RESTART   = "YENİDEN BAŞLA";
				TEXT_SELECT_PLAYERS = "OYUNCU SAYISINI SEÇ!";
				TEXT_SELECT_COLOR = "RENK SEÇ";
				
				TEXT_HELP_VALUE = "DEĞER: %s";
				TEXT_HELP_VALUE_PTS = "DEĞER: +%s puan";
				TEXT_DIGIT_VALUE = "KARTTAKİ RAKAM";
				TEXT_UNO_RULE_VALUE = "RAKİPLERİN İÇİN DE TIKLAMAYI UNUTMA!";
				TEXT_WELCOME = "FOUR COLORS’A HOŞGELDİN!";
				TEXT_ACTION_CARD = "AKSİYON KARTI";
				TEXT_SKIP_CARD = "ATLA KARTI";
				TEXT_REVERSE_CARD = "TERS KARTI";
				TEXT_WILD_CARD = "VAHŞİ KART";
				TEXT_WILD_THREE_CARD = "VAHŞİ +3";
				TEXT_UNO_RULE = "1 KURAL";
				TEXT_SKIP = "ATLA";

				TEXT_TUTORIAL1 = "KARTLARI RENK VEYA SAYIYA GÖRE EŞLEŞTİR, ELİNDEKİ KARTLARI İLK BİTİREN SEN OL!\n\nKAZANAN OYUNCU, DİĞER OYUNCULARIN ELİNDE KALAN KARTLARIN DEĞERİ KADAR PUAN KAZANIR. OYUNU KAZANMAK İÇİN %s PUANA ULAŞ!";
				TEXT_TUTORIAL2 = "AKSİYON KARTLARI OYUNU KARIŞTIRACAK!\n\n2 ÇEK: SIRADAKİ OYUNCUYU 2 KART ÇEKMEYE ZORLAR VE SIRASINI ATLATIR";
				TEXT_TUTORIAL3 = "ATLAMA KARTI: SIRADAKİ OYUNCUNUN SIRASINI ATLATIR";
				TEXT_TUTORIAL4 = "YÖN DEĞİŞTİRME: OYUNUN İLERLEME YÖNÜNÜ DEĞİŞTİRİR";
				TEXT_TUTORIAL5 = "JOKER TÜM KARTLARIN ÜSTÜNE ATILABİLİR VE KARTLARIN RENGİNİ DEĞİŞTİRMEYİ SAĞLAR";
				TEXT_TUTORIAL6 = "JOKER 3: KARTLARIN RENGİNİ DEĞİŞTİRMEYİ VE SIRADAKİ OYUNCUYA 3 KART ÇEKTİRMEYİ SAĞLAYAN ÖZEL BİR KARTTIR. BU KARTI KULLANABİLMEK İÇİN OYNAYABİLECEĞİN BAŞKA KART KALMAMIŞ OLMALIDIR";
				TEXT_TUTORIAL7 = "SADECE BİR KARTIN KALDIĞINDA ' 1 ' DÜĞMESİNE BASMAYI UNUTMA.\n\nEĞER BASMAZSAN VE BİR RAKİP FARK EDERSE, %s CEZA KARTI ALIRSIN.";

				TEXT_PLAYER_1 = "OYUNCU 1";
				TEXT_PLAYER_2 = "OYUNCU 2";
				TEXT_PLAYER_3 = "OYUNCU 3";
				TEXT_PLAYER_4 = "OYUNCU 4";
				TEXT_ALERT_1 = "%s SENİN YERİNE ' 1 'E TIKLADI... \n\n%s CEZA KARTI AL";
				TEXT_ALERT_2 = "%s ' 1 'E TIKLAMADIĞI İÇİN %s CEZA KARTI ALDI";
				TEXT_ALERT_3 = " ' 1 'E BASMADIN AMA KİMSE FARK ETMEDİ. \n\nŞİMDİLİK GÜVENDESİN...";
				TEXT_SUMMARY = "ÖZET";
				TEXT_PTS_TO_WINNER = "Kazanana %s puan";
				TEXT_WINNER = "KAZANAN! \n +%s puan";
				TEXT_PLAYER_WON ="%s OYUNU KAZANDI!";

				TEXT_MULTIPLAYER = "ÇOK OYUNCULU";
				TEXT_MULTIPLAYER_EXPL = "ÇEVRİMİÇİ OYNA";
				TEXT_TRAINING = "EĞİTİM";
				TEXT_TRAINING_EXPL = "AI'YE KARŞI OYNA";
				
				break;
		 }
		 case LANG_AR:{
			 TEXT_GAMEOVER  = "تهانينا! لقد فزت!";
				TEXT_LOSE = "عذرًا، فاز اللاعب %s بهذه المباراة";
				TEXT_SCORE     = "نتائجك";
				TEXT_RESTART   = "إعادة البدء";
				TEXT_SELECT_PLAYERS = "حدد عدد اللاعبين!";
				TEXT_SELECT_COLOR = "حدد لونًا";
				
				TEXT_HELP_VALUE = "القيمة: %s";
				TEXT_HELP_VALUE_PTS = "القيمة: +%s نقطة";
				TEXT_DIGIT_VALUE = "الرقم على البطاقة";
				TEXT_UNO_RULE_VALUE = "تذكّر أن تضغط أيضًا لخصومك!";
				TEXT_WELCOME = "مرحبًا بك في FOUR COLORS!";
				TEXT_ACTION_CARD = "بطاقة حركة";
				TEXT_SKIP_CARD = "بطاقة تخطي";
				TEXT_REVERSE_CARD = "بطاقة عكس";
				TEXT_WILD_CARD = "بطاقة جوكر";
				TEXT_WILD_THREE_CARD = "جوكر +3";
				TEXT_UNO_RULE = "قاعدة 1";
				TEXT_SKIP = "تخطي";
				
				TEXT_TUTORIAL1 = "طابِق البطاقات حسب اللون أو الرقم وكن أول من يتخلص منها!\n\nسيكون رصيد الفائز مساوياً لقيمة بطاقات اللاعبين الآخرين. اجمع %s نقطة للفوز باللعبة!";
				TEXT_TUTORIAL2 = "بطاقات الحركة ستغير مجرى اللعبة!\n\nبطاقة اسحب اثنتين تُجبر اللاعب التالي على سحب بطاقتين والتنازل عن دوره";
				TEXT_TUTORIAL3 = "بطاقة التخطي توقف اللاعب التالي";
				TEXT_TUTORIAL4 = "بطاقة العكس تغيّر اتجاه اللعب";
				TEXT_TUTORIAL5 = "يمكن وضع البطاقة الجوكر على أي بطاقة في أي وقت، وتتيح لك تغيير اللون المطلوب للعب";
				TEXT_TUTORIAL6 = "بطاقة الجوكر +3 هي بطاقة خاصة تتيح لك تغيير اللون وتُجبر اللاعب التالي على سحب 3 بطاقات. لا يمكنك استخدامها إلا إذا لم يكن لديك أي بطاقات أخرى بديلة للعب";
				TEXT_TUTORIAL7 = "لا تنسَ الضغط على زر '1' عندما يتبقى لك بطاقة واحدة فقط.\n\nإذا لم تضغط عليه ولاحظ خصم ذلك، فسوف تستلم %s بطاقات عقوبة.";


				TEXT_PLAYER_1 = "اللاعب 1";
				TEXT_PLAYER_2 = "اللاعب 2";
				TEXT_PLAYER_3 = "اللاعب 3";
				TEXT_PLAYER_4 = "اللاعب 4";
				TEXT_ALERT_1 = "%s نَقَرَ ' 1 ' بَدَلَكَ... \n\nخُذ %s بَطَاقَات عُقُوبَة";
				TEXT_ALERT_2 = "%s تَلَقَّى %s بَطَاقَات عُقُوبَة لِعَدَم الضَّغْط عَلَى ' 1 '";
				TEXT_ALERT_3 = "لَمْ تَضْغَط ' 1 ' وَلَكِنْ لَمْ يُلاحِظ أَحَد. \n\nأَنْتَ فِي أَمَان... حَتّى الآن...";

				TEXT_SUMMARY = "الملخص";
				TEXT_PTS_TO_WINNER = "%s نقطة للفائز";
				TEXT_WINNER = "فائز! \n +%s نقطة";
				TEXT_PLAYER_WON ="%s فاز باللعبة!";

				TEXT_MULTIPLAYER = "متعدد اللاعبين";
				TEXT_MULTIPLAYER_EXPL = "اللعب عبر الإنترنت";
				TEXT_TRAINING = "تدريب";
				TEXT_TRAINING_EXPL = "العب ضد AI";
				
				break;
		 }
		 case LANG_HI:{
				TEXT_GAMEOVER  = "बधाई हो! आप जीत गए हैं!";
				TEXT_LOSE = "माफ़ करें, खिलाड़ी %s यह गेम जीत गया";
				TEXT_SCORE     = "आपका स्कोर";
				TEXT_RESTART   = "रीस्टार्ट करें";
				TEXT_SELECT_PLAYERS = "खिलाड़ियों की संख्या चुनें!";
				TEXT_SELECT_COLOR = "एक रंग चुनें";
				
				TEXT_HELP_VALUE = "मूल्य: %s";
				TEXT_HELP_VALUE_PTS = "मूल्य: +%s अंक";
				TEXT_DIGIT_VALUE = "कार्ड पर अंक";
				TEXT_UNO_RULE_VALUE = "याद रखें इसे अपने प्रतिद्वंद्वियों के लिए भी क्लिक करें!";
				TEXT_WELCOME = "FOUR COLORS में आपका स्वागत है!";
				TEXT_ACTION_CARD = "एक्शन कार्ड";
				TEXT_SKIP_CARD = "स्किप कार्ड";
				TEXT_REVERSE_CARD = "रिवर्स कार्ड";
				TEXT_WILD_CARD = "वाइल्ड कार्ड";
				TEXT_WILD_THREE_CARD = "वाइल्ड +3";
				TEXT_UNO_RULE = "1 नियम";
				TEXT_SKIP = "स्किप";
				
				TEXT_TUTORIAL1 = "रंग या संख्या के अनुसार कार्डों का मिलान करें और उनसे छुटकारा पाने वाले पहले व्यक्ति बनें!\n\nविजेता का स्कोर अन्य खिलाड़ियों के कार्डों के मान के समान होगा. गेम जीतने के लिए %s पॉइंट तक पहुंचें!";
				TEXT_TUTORIAL2 = "एक्शन कार्ड गेम को मिक्स कर देंगे!\n\nड्रॉ दो अगले खिलाड़ी को दो कार्ड लेने के लिए मजबूर करता है और बारी छोड़नी पड़ती है";
				TEXT_TUTORIAL3 = "कार्ड छोड़ें अगले खिलाड़ी को रोकता है";
				TEXT_TUTORIAL4 = "रिवर्स कार्ड गेम के अनुसार स्विच करता है";
				TEXT_TUTORIAL5 = "वाइल्ड कार्ड किसी भी समय किसी भी कार्ड पर रखा जा सकता है और यह आपको खेलने के लिए रंग बदलने देता है";
				TEXT_TUTORIAL6 = "वाइल्ड ड्रॉ थ्री एक स्पेशल वाइल्ड है जो आपको रंग बदलने देता है और अगले खिलाड़ी को 3 कार्ड लेने के लिए मजबूर करता है. इस कार्ड का इस्तेमाल करने के लिए आपके पास खेलने के लिए कोई अन्य वैकल्पिक कार्ड नहीं होना चाहिए";
				TEXT_TUTORIAL7 = "मत भूलो ' 1 ' बटन दबाना जब तुम्हारे पास केवल एक कार्ड बचेगा।\n\nअगर तुम नहीं दबाते और कोई प्रतिद्वंद्वी ध्यान देता है, तो तुम्हें %s दंड कार्ड मिलेंगे।";

				TEXT_PLAYER_1 = "खिलाड़ी 1";
				TEXT_PLAYER_2 = "खिलाड़ी 2";
				TEXT_PLAYER_3 = "खिलाड़ी 3";
				TEXT_PLAYER_4 = "खिलाड़ी 4";
				TEXT_ALERT_1 = "%s ने तुम्हारे लिए ' 1 ' दबा दिया... \n\n%s दंड कार्ड लो";
				TEXT_ALERT_2 = "%s को ' 1 ' न दबाने पर %s दंड कार्ड मिले";
				TEXT_ALERT_3 = "तुमने ' 1 ' नहीं दबाया लेकिन किसी ने ध्यान नहीं दिया। \n\nअभी के लिए तुम सुरक्षित हो...";
				TEXT_SUMMARY = "सारांश";
				TEXT_PTS_TO_WINNER = "विजेता को %s पॉइंट";
				TEXT_WINNER = "विजेता! \n +%s अंक";
				TEXT_PLAYER_WON ="%s गेम जीत गया!";

				TEXT_MULTIPLAYER = "मल्टीप्लेयर";
				TEXT_MULTIPLAYER_EXPL = "ऑनलाइन खेलें";
				TEXT_TRAINING = "प्रशिक्षण";
				TEXT_TRAINING_EXPL = "AI के खिलाफ खेलें";
					
				break;
		 }
		 case LANG_ID:{
			 TEXT_GAMEOVER  = "SELAMAT! KAMU MENANG!";
				TEXT_LOSE = "MAAF, PEMAIN %s MEMENANGI PERMAINAN INI";
				TEXT_SCORE     = "SKOR KAMU";
				TEXT_RESTART   = "MULAI ULANG";
				TEXT_SELECT_PLAYERS = "PILIH JUMLAH PEMAIN!";
				TEXT_SELECT_COLOR = "PILIH WARNA";
				
				TEXT_HELP_VALUE = "NILAI: %s";
				TEXT_HELP_VALUE_PTS = "NILAI: +%s poin";
				TEXT_DIGIT_VALUE = "ANGKA DI KARTU";
				TEXT_UNO_RULE_VALUE = "JANGAN LUPA KLIK UNTUK LAWANMU JUGA!";
				TEXT_WELCOME = "SELAMAT DATANG DI FOUR COLORS!";
				TEXT_ACTION_CARD = "KARTU AKSI";
				TEXT_SKIP_CARD = "KARTU LEWATI";
				TEXT_REVERSE_CARD = "KARTU BALIK";
				TEXT_WILD_CARD = "KARTU WILD";
				TEXT_WILD_THREE_CARD = "WILD +3";
				TEXT_UNO_RULE = "1 ATURAN";
				TEXT_SKIP = "LEWATI";
				
				TEXT_TUTORIAL1 = "COCOKKAN KARTU BERDASARKAN WARNA ATAU ANGKA DAN JADILAH YANG PERTAMA MENYINGKIRKAN PESAING!\n\nSKOR PEMENANG AKAN SAMA DENGAN NILAI KARTU PEMAIN LAIN. RAIH %s POIN UNTUK MEMENANGI PERMAINAN!";
				TEXT_TUTORIAL2 = "KARTU AKSI AKAN MEMERIAHKAN PERMAINAN!\n\nAMBIL DUA MEMAKSA PEMAIN BERIKUTNYA UNTUK MENGAMBIL DUA KARTU DAN MENGORBANKAN GILIRAN";
				TEXT_TUTORIAL3 = "KARTU LEWATI MENGHENTIKAN PEMAIN BERIKUTNYA";
				TEXT_TUTORIAL4 = "KARTU REVERSE MEMBALIK ARAH GILIRAN";
				TEXT_TUTORIAL5 = "KARTU LIAR BISA DITARUH DI ATAS KARTU APA SAJA KAPAN SAJA DAN MEMUNGKINKANMU MENGUBAH WARNA KARTU YANG DIMAINKAN";
				TEXT_TUTORIAL6 = "KARTU LIAR TIGA ADALAH KARTU LIAR SPESIAL YANG MEMUNGKINKANMU UNTUK MENGUBAH WARNA DAN MEMAKSA PEMAIN BERIKUTNYA UNTUK MENGAMBIL 3 KARTU. UNTUK MENGGUNAKAN KARTU INI, KAMU HARUS DALAM KONDISI YANG TIDAK PUNYA ALTERNATIF KARTU UNTUK DIMAINKAN";
				TEXT_TUTORIAL7 = "JANGAN LUPA TEKAN TOMBOL ' 1 ' KETIKA KAMU HANYA MEMILIKI SATU KARTU TERSISA.\n\nJIKA KAMU TIDAK MENEKANNYA DAN LAWAN MENYADARI, KAMU AKAN MENERIMA %s KARTU HUKUMAN.";

				TEXT_PLAYER_1 = "PEMAIN 1";
				TEXT_PLAYER_2 = "PEMAIN 2";
				TEXT_PLAYER_3 = "PEMAIN 3";
				TEXT_PLAYER_4 = "PEMAIN 4";
				TEXT_ALERT_1 = "%s MENEKAN ' 1 ' UNTUKMU... \n\nAMBIL %s KARTU HUKUMAN";
				TEXT_ALERT_2 = "%s MENDAPATKAN %s KARTU HUKUMAN KARENA TIDAK MENEKAN ' 1 '";
				TEXT_ALERT_3 = "KAMU TIDAK MENEKAN ' 1 ' TAPI TIDAK ADA YANG MENYADARI. \n\nKAMU SELAMAT, UNTUK SEMENTARA...";

				TEXT_SUMMARY = "RANGKUMAN";
				TEXT_PTS_TO_WINNER = "%s poin ke pemenang";
				TEXT_WINNER = "PEMENANG! \n +%s poin";
				TEXT_PLAYER_WON = "%s MEMENANGI PERMAINAN!";
	
				TEXT_MULTIPLAYER = "MULTIPEMAIN";
				TEXT_MULTIPLAYER_EXPL = "MAIN ONLINE";
				TEXT_TRAINING = "LATIHAN";
				TEXT_TRAINING_EXPL = "BERMAIN MELAWAN AI";
				
				break;
		 }
		 case LANG_JA:{
			 TEXT_GAMEOVER  = "おめでとうございます！勝利！";
				TEXT_LOSE = "残念。今回は%s相手の勝利です";
				TEXT_SCORE     = "自己スコア";
				TEXT_RESTART   = "リスタート";
				TEXT_SELECT_PLAYERS = "プレイヤー数を選択してください！";
				TEXT_SELECT_COLOR = "色を選択してください";
				
				TEXT_HELP_VALUE = "値: %s";
				TEXT_HELP_VALUE_PTS = "値: +%s 点";
				TEXT_DIGIT_VALUE = "カードの数字";
				TEXT_UNO_RULE_VALUE = "相手の分もクリックするのを忘れずに！";
				TEXT_WELCOME = "FOUR COLORSへようこそ！";
				TEXT_ACTION_CARD = "アクションカード";
				TEXT_SKIP_CARD = "スキップカード";
				TEXT_REVERSE_CARD = "リバースカード";
				TEXT_WILD_CARD = "ワイルドカード";
				TEXT_WILD_THREE_CARD = "ワイルド +3";
				TEXT_UNO_RULE = "ルール1";
				TEXT_SKIP = "スキップ";
				
				TEXT_TUTORIAL1 = "カードを色や数字で一 致させることで、 いち早く手持ちのカー ドを使い切ってください。\n\n勝者のスコアは、 他のプレイヤーのカードの値と等しい数値です。%s ポイントに到達してゲームに勝利しましょう！";
				TEXT_TUTORIAL2 = "アクションカードでゲームが混乱の渦に！\n\nドロー 2 のカードを出すと、次のプレイヤーがカードを 2 枚引き、そのターンをスキップします";
				TEXT_TUTORIAL3 = "スキップのカー ドを出すと、 次のプレイヤー はそのター ンをスキップします";
				TEXT_TUTORIAL4 = "リバー スのカードを出すと 、カー ドをプレイする順番が逆になります";
				TEXT_TUTORIAL5 = "ワイルドのカー ドはいつでもどのカー ドに対しても使うことができ、 このカー ドを出したプレイヤー はプレイする色を変えることができます";
				TEXT_TUTORIAL6 = "ワイルド・ ドロー 3 のカー ドは特殊なワイルドで、このカー ドを出したプレイヤー は色を変えることができる上に 、その次のプレイヤーに 3  枚カー ドを引かせます。このカ ードは他に出せるカ ードがない時にのみ出すことができます";
				TEXT_TUTORIAL7 = "残り1枚になったら必ず「 1 」ボタンを押すのを忘れないでください。\n\n押さなかったことに相手が気づけば、%s 枚のペナルティカードを受け取ります。";

				TEXT_PLAYER_1 = "プレイヤー 1";
				TEXT_PLAYER_2 = "プレイヤー 2";
				TEXT_PLAYER_3 = "プレイヤー 3";
				TEXT_PLAYER_4 = "プレイヤー 4";
				TEXT_ALERT_1 = "%s があなたの代わりに「 1 」を押しました... \n\nペナルティカードを %s 枚引いてください";
				TEXT_ALERT_2 = "%s は「 1 」を押さなかったため、ペナルティカードを %s 枚受け取りました";
				TEXT_ALERT_3 = "あなたは「 1 」を押しませんでしたが、誰にも気づかれませんでした。 \n\nとりあえず無事です...";

				TEXT_SUMMARY = "要約";
				TEXT_PTS_TO_WINNER = "%s ポイントを勝者に授与";
				TEXT_WINNER = "勝者！ \n +%s 点";
				TEXT_PLAYER_WON ="%s がゲームに勝利しました！";

				TEXT_MULTIPLAYER = "マルチプレイヤー";
				TEXT_MULTIPLAYER_EXPL = "オンラインでプレイ";
				TEXT_TRAINING = "トレーニング";
				TEXT_TRAINING_EXPL = "AIと対戦する";
				
				break;
		 }
		 case LANG_ZH:{
			 TEXT_GAMEOVER  = "恭喜！您赢了！";
				TEXT_LOSE = "抱歉，玩家 %s 赢了这场游戏";
				TEXT_SCORE     = "您的得分";
				TEXT_RESTART   = "重新开始";
				TEXT_SELECT_PLAYERS = "选择玩家数量！";
				TEXT_SELECT_COLOR = "选择颜色";
				
				TEXT_HELP_VALUE = "数值: %s";
				TEXT_HELP_VALUE_PTS = "数值: +%s 分";
				TEXT_DIGIT_VALUE = "牌上的数字";
				TEXT_UNO_RULE_VALUE = "记得也要帮对手点击！";
				TEXT_WELCOME = "欢迎来到 FOUR COLORS!";
				TEXT_ACTION_CARD = "功能牌";
				TEXT_SKIP_CARD = "跳过牌";
				TEXT_REVERSE_CARD = "反转牌";
				TEXT_WILD_CARD = "万能牌";
				TEXT_WILD_THREE_CARD = "万能 +3";
				TEXT_UNO_RULE = "规则 1";
				TEXT_SKIP = "跳过";
				
				TEXT_TUTORIAL1 = "按颜色或数字匹配纸牌， 出掉这些纸牌！\n\n获胜者的得分将与其他玩家纸牌的分值相同。 达到 %s  积分即可赢得游戏！";
				TEXT_TUTORIAL2 = "行动牌行会打乱游戏局面！ \n\n 抽两张纸牌会迫使下家选择两张纸牌并放弃回合";
				TEXT_TUTORIAL3 = "跳过牌可让下家停止出牌一次";
				TEXT_TUTORIAL4 = "反转牌可以反转出牌方向";
				TEXT_TUTORIAL5 = "万能牌在任何条件下均可打出 ，并改变下家出牌颜色";
				TEXT_TUTORIAL6 = "Wild Draw 3  是一种特殊的万能牌， 它允许您改变下家出牌颜色并让下家选择  3  张纸牌。 您必须在无其他符合颜色或数 字的纸牌可出的情况下才能使用  WILD Draw 3";
				TEXT_TUTORIAL7 = "当你只剩下一张牌时，不要忘记按下 ' 1 ' 按钮。\n\n如果你没有按下而对手注意到了，你将抽取 %s 张罚牌。";

				TEXT_PLAYER_1 = "1 号玩家";
				TEXT_PLAYER_2 = "2 号玩家";
				TEXT_PLAYER_3 = "3 号玩家";
				TEXT_PLAYER_4 = "4 号玩家";
				TEXT_ALERT_1 = "%s 替你点击了 ' 1 '... \n\n抽取 %s 张罚牌";
				TEXT_ALERT_2 = "%s 因未点击 ' 1 ' 而受到 %s 张罚牌";
				TEXT_ALERT_3 = "你没有按 ' 1 '，但没人发现。 \n\n暂时安全...";
				TEXT_SUMMARY = "总结";
				TEXT_PTS_TO_WINNER = "赢家获得 %s 积分";
				TEXT_WINNER = "胜利者！ \n +%s 分";
				TEXT_PLAYER_WON ="%s 赢了这场游戏！";

				TEXT_MULTIPLAYER = "多人游戏";
				TEXT_MULTIPLAYER_EXPL = "在线游戏";
				TEXT_TRAINING = "训练";
				TEXT_TRAINING_EXPL = "与AI对战";
				
				break;
		 }
	}

}