var TEXT_ORIGINAL_LANGUAGE = {};
TEXT_ORIGINAL_LANGUAGE["en"] = "English";
TEXT_ORIGINAL_LANGUAGE["ru"] = "Русский";
TEXT_ORIGINAL_LANGUAGE["es"] = "Español";
TEXT_ORIGINAL_LANGUAGE["fr"] = "Français";
TEXT_ORIGINAL_LANGUAGE["de"] = "Deutsch";
TEXT_ORIGINAL_LANGUAGE["pt"] = "Português";
TEXT_ORIGINAL_LANGUAGE["it"] = "Italiano";
TEXT_ORIGINAL_LANGUAGE["ar"] = "العربية";
TEXT_ORIGINAL_LANGUAGE["hi"] = "हिंदी";
TEXT_ORIGINAL_LANGUAGE["tr"] = "Türkçe";
TEXT_ORIGINAL_LANGUAGE["id"] = "bahasa Indonesia";
TEXT_ORIGINAL_LANGUAGE["ja"] = "日本語";
TEXT_ORIGINAL_LANGUAGE["zh"] = "简体中文";

var TEXT_CREDITS_URL = "https://www.codethislab.com";
var TEXT_MY_PROFILE = "My Profile";
var TEXT_EDIT_PROFILE = "Edit Profile";
var TEXT_LOGIN = "Login";
var TEXT_SETTINGS = "Settings";
var TEXT_LANGUAGE = "Language";
var TEXT_FULLSCREEN_OFF = "Full Screen Mode Off";
var TEXT_FULLSCREEN_ON = "Full Screen Mode On";
var TEXT_MUSIC_OFF = "Music Off";
var TEXT_MUSIC_ON = "Music On";
var TEXT_SFX_ON = "Sfx On";
var TEXT_SFX_OFF = "Sfx Off";
var TEXT_ANIMATION_ON = "Animations On";
var TEXT_ANIMATION_OFF = "Animations Off";
var TEXT_GAME_OPTION = "Game Option";
var TEXT_MAIN_MENU = "Main Menu";
var TEXT_SB_RESTART = "Restart";
var TEXT_LEADERBOARD = "Leaderboard";
var TEXT_ONLINE_ROOMS = "Online Rooms";
var TEXT_REPORT_BUG = "Report a bug";
var TEXT_STATS = "Stats";
var TEXT_ARE_YOU_SURE = "ARE YOU SURE?";
var TEXT_MORE_GAMES = "More Games";
var TEXT_MORE_GAMES_SUB = "New Free Titles";
var TEXT_MORE_GAMES_EXP = "DO YOU WANNA PLAY MORE GAMES?\n\nCLICK OK TO WATCH OUR CATALOG";
var TEXT_CREDITS = "Credits";
var TEXT_LOGOUT = "Sign Out";
var TEXT_REGISTER = "Register";
var TEXT_CLOSE = "Close";
var TEXT_EMAIL = "Email address";
var TEXT_PWD = "Password";
var TEXT_SUBMIT = "Submit";
var TEXT_NO_LEADERBOARD = "NO LEADERBOARD AVAILABLE";
var TEXT_PLS_LOGIN = "PLEASE LOGIN TO ACCESS THIS FEATURE";
var TEXT_FEATURED_GAMES = "Featured Games";
var TEXT_OTHER_GAMES = "Other Games";
var TEXT_SEND_EMAIL = "Please write us at";
var TEXT_RANKING = "RANKING";
var TEXT_WINS = "WINS";
var TEXT_DEUCES = "DEUCES";
var TEXT_LOSSES = "DEFEATS";
var TEXT_WIN_PERC = "WIN%";
var TEXT_HELP_GAME_RULE = "Game Rules";

var TEXT_GUEST = "GUEST";
var TEXT_STATS_NO_LOGIN = "LOGIN TO SAVE YOUR PROGRESSES";
var TEXT_PLAY_GUEST = "PLAY AS GUEST";
var TEXT_LOGIN = "LOGIN"; 
var TEXT_REGISTER = "CREATE ACCOUNT";
var TEXT_FIELDS_NOT_FILLED = "PLEASE FILL ALL FIELDS";
var TEXT_MAX_LEN_PWD = "(Max 10 chars)";
var TEXT_SYS_CONFIRM_PWD = "Confirm Password";
var TEXT_SYS_REGISTRATION  = "Registration Panel";
var TEXT_PWD_NOT_MATCHING = "PASSWORD DOESN'T MATCH";
var TEXT_PWD_TOO_SHORT = "PASSWORD MUST BE AT LEAST 3 CHARACTERS LONG";
var TEXT_PWD_TOO_LONG = "PASSWORD TOO LONG! MAX 10 CHARS";
var TEXT_EMAIL_NOT_VALID = "Insert a valid e-mail";
var TEXT_ERR_USER_ALREADY_REGISTERED = "The username is already registered";
var TEXT_ERR_EMAIL_ALREADY_REGISTERED = "The email is already registered";
var TEXT_GENERIC_REGISTER_ERR = "REGISTRATION FAILED";
var TEXT_PWD_FORGOT = "Forgot Password?";
var TEXT_PWD_RECOVER = "Check your email to reset your password";
var TEXT_FIND_OPPONENTS = "Finding opponents...";
var TEXT_INVALID_PASSWORD = "PASSWORD NOT VALID";
var TEXT_GENERIC_LOGIN_FAILED = "LOGIN FAILED!";
var TEXT_INVALID_USER = "NICKNAME NOT FOUND";
var TEXT_YES = "YES";
var TEXT_NO = "NO";
var TEXT_DELETE_USER = "DELETE USER";

/*********LEADERBOARD TEXTS******************/
var TEXT_LEADERBOARD = "Leaderboard";
var TEXT_POSITION = "#";
var TEXT_RANK = "Rank";
var TEXT_NICKNAME = "Nickname";
var TEXT_POINTS = "Score";
var TEXT_GENERAL_LEADERBOARD = "General";
var TEXT_MONTHLY_LEADERBOARD = "Monthly";
var TEXT_DAILY_LEADERBOARD = "Daily";
/***************************/
var TEXT_TERMS_OF_USE = "Terms of Use (EULA)";
var TEXT_PRIVACY = "Privacy Policy";
var TEXT_TERMS_OF_USE_URL = "";
var TEXT_PRIVACY_URL = "https://codethislab.com/code-this-lab-srl-apps-privacy-policy-en/";
var TEXT_PERSONAL_DATA_MANAGEMENT = "Personal Data Management";
var TEXT_REMOVE_ADS = "Remove Ads";
var	TEXT_SVC_RESTORE = "Restore";

function refreshLanguageGUIController(){
	
	switch(s_iCurLang){
		case LANG_EN:{
			TEXT_CREDITS_URL = "https://www.codethislab.com";
			TEXT_MY_PROFILE = "My Profile";
			TEXT_EDIT_PROFILE = "Edit Profile";
			TEXT_LOGIN = "Login";
			TEXT_SETTINGS = "Settings";
			TEXT_LANGUAGE = "Language";
			TEXT_FULLSCREEN_OFF = "Full Screen Mode Off";
			TEXT_FULLSCREEN_ON =  "Full Screen Mode On";
			TEXT_MUSIC_OFF = "Music Off";
			TEXT_MUSIC_ON = "Music On";
			TEXT_SFX_ON = "Sfx On";
			TEXT_SFX_OFF = "Sfx Off";
			TEXT_ANIMATION_ON = "Animations On";
			TEXT_ANIMATION_OFF = "Animations Off";
			TEXT_GAME_OPTION = "Game Option";
			TEXT_MAIN_MENU = "Main Menu";
			TEXT_SB_RESTART = "Restart";
			TEXT_LEADERBOARD = "Leaderboard";
			TEXT_ONLINE_ROOMS = "Online Rooms";
			TEXT_REPORT_BUG = "Report a Bug";
			TEXT_STATS = "Stats";
			TEXT_ARE_YOU_SURE = "ARE YOU SURE?";
			TEXT_MORE_GAMES = "More Games";
			TEXT_MORE_GAMES_SUB = "New Free Titles";
			TEXT_MORE_GAMES_EXP = "DO YOU WANNA PLAY MORE GAMES?\n\nCLICK OK TO WATCH OUR CATALOG";
			TEXT_CREDITS = "Credits";
			TEXT_LOGOUT = "Sign Out";
			TEXT_REGISTER = "Register";
			TEXT_CLOSE = "Close";
			TEXT_EMAIL = "Email address";
			TEXT_PWD = "Password";
			TEXT_SUBMIT = "Submit";
			TEXT_NO_LEADERBOARD = "NO LEADERBOARD AVAILABLE";
			TEXT_PLS_LOGIN = "PLEASE LOGIN TO ACCESS THIS FEATURE";
			TEXT_FEATURED_GAMES = "Featured Games";
			TEXT_OTHER_GAMES = "Other Games";
			TEXT_SEND_EMAIL = "Please write us at";
			TEXT_RANKING = "RANKING";
			TEXT_WINS = "WINS";
			TEXT_DEUCES = "DEUCES";
			TEXT_LOSSES = "DEFEATS";
			TEXT_WIN_PERC = "WIN%";
			TEXT_HELP_GAME_RULE = "Game Rules";
			
			TEXT_GUEST = "GUEST";
			TEXT_STATS_NO_LOGIN = "LOGIN TO SAVE YOUR PROGRESSES";
			TEXT_PLAY_GUEST = "PLAY AS GUEST";
			TEXT_LOGIN = "LOGIN";
			TEXT_REGISTER = "CREATE ACCOUNT";
			TEXT_FIELDS_NOT_FILLED = "PLEASE FILL ALL FIELDS";
			TEXT_MAX_LEN_PWD = "(Max 10 chars)";
			TEXT_SYS_CONFIRM_PWD = "Confirm Password";
			TEXT_SYS_REGISTRATION  = "Registration Panel";
			TEXT_PWD_NOT_MATCHING = "PASSWORD DOESN'T MATCH";
			TEXT_PWD_TOO_SHORT = "PASSWORD MUST BE AT LEAST 3 CHARACTERS LONG";
			TEXT_PWD_TOO_LONG = "PASSWORD TOO LONG! MAX 10 CHARS";
			TEXT_EMAIL_NOT_VALID = "Insert a valid e-mail";
			TEXT_ERR_USER_ALREADY_REGISTERED = "The username is already registered";
			TEXT_ERR_EMAIL_ALREADY_REGISTERED = "The email is already registered";
			TEXT_GENERIC_REGISTER_ERR = "REGISTRATION FAILED";
			TEXT_INVALID_PASSWORD = "PASSWORD NOT VALID";
			TEXT_PWD_FORGOT = "Forgot Password?";
			TEXT_PWD_RECOVER = "Check your email to reset your password";
			TEXT_FIND_OPPONENTS = "Finding opponents...";
			TEXT_GENERIC_LOGIN_FAILED = "LOGIN FAILED!";
			TEXT_INVALID_USER = "NICKNAME NOT FOUND";
			TEXT_YES = "YES";
			TEXT_NO = "NO";
			TEXT_DELETE_USER = "DELETE USER";
			
			TEXT_LEADERBOARD = "Leaderboard";
			TEXT_POSITION = "#";
			TEXT_RANK = "Rank";
			TEXT_NICKNAME = "Nickname";
			TEXT_POINTS = "Score";
			TEXT_GENERAL_LEADERBOARD = "General";
			TEXT_MONTHLY_LEADERBOARD = "Monthly";
			TEXT_DAILY_LEADERBOARD = "Daily";
			
			TEXT_TERMS_OF_USE = "Terms of Use (EULA)";
			TEXT_PRIVACY = "Privacy Policy";
			TEXT_TERMS_OF_USE_URL = "";
			TEXT_PRIVACY_URL = "https://codethislab.com/code-this-lab-srl-apps-privacy-policy-en/";
			TEXT_PERSONAL_DATA_MANAGEMENT = "Personal Data Management";
			TEXT_REMOVE_ADS = "Remove Ads";
			TEXT_SVC_RESTORE = "Restore";
			
			break;
		}
		case LANG_RU:{
			TEXT_CREDITS_URL = "https://www.codethislab.com";
			TEXT_MY_PROFILE = "Мой профиль ";
			TEXT_EDIT_PROFILE = "Редактировать профиль";
			TEXT_LOGOUT = "Выйти";
			TEXT_LOGIN = "Войти";
			TEXT_SETTINGS = "Настройки";
			TEXT_LANGUAGE = "Язык";
			TEXT_FULLSCREEN_OFF = "Режим полного экрана выкл";
			TEXT_FULLSCREEN_ON = "Режим полного экрана вкл";
			TEXT_MUSIC_OFF = "Звук выкл";
			TEXT_MUSIC_ON = "Звук вкл";
			TEXT_SFX_ON = "Sfx Вкл";
			TEXT_SFX_OFF = "Sfx Выкл";
			TEXT_ANIMATION_ON = "Анимация Включена";
			TEXT_ANIMATION_OFF = "Анимация Выключена";
			TEXT_GAME_OPTION = "Опции игры";
			TEXT_MAIN_MENU = "Главное меню";
			TEXT_SB_RESTART = "Перезапуск";
			TEXT_LEADERBOARD = "Таблица лидеров";
			TEXT_ONLINE_ROOMS = "Онлайн-комнаты";
			TEXT_REPORT_BUG = "Сообщить о баге";
			TEXT_STATS = "Статистика";
			TEXT_ARE_YOU_SURE = "УВЕРЕНЫ?";
			TEXT_MORE_GAMES = "Больше игр";
			TEXT_MORE_GAMES_SUB = "Новые Бесплатные Титулы";
			TEXT_MORE_GAMES_EXP = "ВЫ ХОТИТЕ ИГРАТЬ БОЛЬШЕ ИГРЫ?\n\nНАЖМИТЕ OK, ЧТОБЫ ПОСМОТРЕТЬ НАШ КАТАЛОГ";
			TEXT_CREDITS = "Кредиты";
			
			TEXT_REGISTER = "Регистрация";
			TEXT_CLOSE = "Закрыть";
			TEXT_EMAIL = "Адрес электронной почты";
			TEXT_PWD = "Пароль";
			TEXT_SUBMIT = "Отправить";
			TEXT_NO_LEADERBOARD = "ТАБЛИЦА ЛИДЕРОВ НЕДОСТУПНА";
			TEXT_PLS_LOGIN = "ПОЖАЛУЙСТА, ВОЙДИТЕ, ЧТОБЫ ПОЛЬЗОВАТЬСЯ ЭТОЙ ФУНКЦИЕЙ";
			TEXT_FEATURED_GAMES = "Рекомендуемые игры";
			TEXT_OTHER_GAMES = " Другие игры";
			TEXT_SEND_EMAIL = "Пожалуйста, напишите нам на";
			TEXT_RANKING = "Рейтинг";
			TEXT_WINS = "ПОБЕДЫ";
			TEXT_DEUCES = "НИЧЬИ";
			TEXT_LOSSES = "ПОРАЖЕНИЯ";
			TEXT_WIN_PERC = "% ПОБЕД";
			TEXT_HELP_GAME_RULE = "Правила игры";
			
			TEXT_GUEST = "ГОСТЬ";
			
			TEXT_STATS_NO_LOGIN = "ВОЙДИТЕ, ЧТОБЫ СОХРАНИТЬ СВОИ ПРОГРЕССЫ";
			TEXT_PLAY_GUEST = "ИГРАТЬ КАК ГОСТЬ";
			TEXT_LOGIN = "ЛОГИН";
			TEXT_REGISTER = "СОЗДАТЬ АККАУНТ";
			TEXT_FIELDS_NOT_FILLED = "ЗАПОЛНИТЕ ВСЕ ПОЛЯ";
			TEXT_MAX_LEN_PWD = "(макс. 10 символов)";
			TEXT_SYS_CONFIRM_PWD = "Подтвердите пароль";
			TEXT_SYS_REGISTRATION  = "Панель регистрации";
			TEXT_PWD_NOT_MATCHING = "ПАРОЛИ НЕ СОВПАДАЮТ";
			TEXT_PWD_TOO_SHORT = "В ПАРОЛЕ ДОЛЖНО БЫТЬ НЕ МЕНЬШЕ 3 СИМВОЛОВ";
			TEXT_PWD_TOO_LONG = "СЛИШКОМ ДЛИННЫЙ ПАРОЛЬ! НЕ БОЛЬШЕ 10 СИМВОЛОВ";
			TEXT_EMAIL_NOT_VALID = "Введите действительный адрес электронной почты";
			TEXT_ERR_USER_ALREADY_REGISTERED = "Имя пользователя уже зарегистрировано";
			TEXT_ERR_EMAIL_ALREADY_REGISTERED = "Электронная почта уже зарегистрирована";
			TEXT_GENERIC_REGISTER_ERR = "РЕГИСТРАЦИЯ НЕ УДАЛАСЬ";
			TEXT_INVALID_PASSWORD = "ПАРОЛЬ НЕДОПУСТИМ";
			TEXT_PWD_FORGOT = "Забыли пароль";
			TEXT_PWD_RECOVER = "Проверьте свою электронную почту, чтобы сбросить пароль";
			TEXT_FIND_OPPONENTS = "Поиск противника...";
			TEXT_GENERIC_LOGIN_FAILED = "Ошибка входа!";
			TEXT_INVALID_USER = "Никнейм не найден";
			TEXT_YES = "Да";
			TEXT_NO = "Нет";
			TEXT_DELETE_USER = "Удалить пользователя";
			
			TEXT_LEADERBOARD = "Таблица лидеров";
			TEXT_POSITION = "#";
			TEXT_RANK = "Ранг";
			TEXT_NICKNAME = "Никнейм";
			TEXT_POINTS = "Счет";
			TEXT_GENERAL_LEADERBOARD = "Общий";
			TEXT_MONTHLY_LEADERBOARD = "Ежемесячный";
			TEXT_DAILY_LEADERBOARD = "Ежедневный";
			
			TEXT_TERMS_OF_USE = "Условия использования (EULA)";
			TEXT_PRIVACY = "Политика конфиденциальности";
			TEXT_TERMS_OF_USE_URL = "";
			TEXT_PRIVACY_URL = "https://codethislab.com/code-this-lab-srl-apps-privacy-policy-en/";
			TEXT_PERSONAL_DATA_MANAGEMENT = "Управление персональными данными";
			TEXT_REMOVE_ADS = "Убрать рекламу";
			TEXT_SVC_RESTORE = "Восстановить";
			
			break;
		}
		case LANG_ES:{
			TEXT_MY_PROFILE = "Mi Perfil";
			TEXT_CREDITS_URL = "https://www.codethislab.com";
			TEXT_EDIT_PROFILE = "Editar Perfil";
			TEXT_LOGOUT = "Cerrar Sesión";
			TEXT_LOGIN = "Iniciar Sesión";
			TEXT_SETTINGS = "Configuración";
			TEXT_LANGUAGE = "Idioma";
			TEXT_FULLSCREEN_OFF = "Modo Pantalla Completa Desactivado";
			TEXT_FULLSCREEN_ON = "Modo Pantalla Completa Activado";
			TEXT_MUSIC_OFF = "Audio Desactivado";
			TEXT_MUSIC_ON = "Audio Activado";
			TEXT_SFX_ON = "Sfx Encendido";
			TEXT_SFX_OFF = "Sfx Apagado";
			TEXT_ANIMATION_ON = "Animaciones Activadas";
			TEXT_ANIMATION_OFF = "Animaciones Desactivadas";
			TEXT_GAME_OPTION = "Opción de Juego";
			TEXT_MAIN_MENU = "Menú Principal";
			TEXT_SB_RESTART = "Reiniciar";
			TEXT_LEADERBOARD = "Tabla de Clasificación";
			TEXT_ONLINE_ROOMS = "Salas en Línea";
			TEXT_REPORT_BUG = "Reportar un Error";
			TEXT_STATS = "Estadísticas";
			TEXT_ARE_YOU_SURE = "¿SEGURO?";
			TEXT_MORE_GAMES = "Más Juegos";
			TEXT_MORE_GAMES_SUB = "Nuevos Títulos Gratuitos";
			TEXT_MORE_GAMES_EXP = "¿QUIERES JUGAR MÁS JUEGOS?\n\nHAGA CLIC EN ACEPTAR PARA VER NUESTRO CATÁLOGO";
			TEXT_CREDITS = "Créditos";
			TEXT_REGISTER = "Registrarse";
			TEXT_CLOSE = "Cerrar";
			TEXT_EMAIL = "Dirección de Correo Electrónico";
			TEXT_PWD = "Contraseña";
			TEXT_SUBMIT = "Enviar";
			TEXT_NO_LEADERBOARD = "NO HAY TABLA DE CLASIFICACIÓN DISPONIBLE";
			TEXT_PLS_LOGIN = "POR FAVOR INICIA SESIÓN PARA ACCEDER A ESTA FUNCIÓN";
			TEXT_FEATURED_GAMES = "Uegos Destacados";
			TEXT_OTHER_GAMES = "Otros Juegos";
			TEXT_SEND_EMAIL = "Por favor escríbanos a";
			TEXT_RANKING = "CLASIFICACIÓN";
			TEXT_WINS = "VICTORIAS";
			TEXT_DEUCES = "EMPATES";
			TEXT_LOSSES = "DERROTAS";
			TEXT_WIN_PERC = "% VICTORIAS";
			TEXT_HELP_GAME_RULE = "Reglas del juego";

			TEXT_GUEST = "INVITADO";
			
			TEXT_STATS_NO_LOGIN = "INICIA SESIÓN PARA GUARDAR TUS PROGRESOS";
			TEXT_PLAY_GUEST = " JUGAR COMO INVITADO";
			TEXT_LOGIN = "INICIAR SESIÓN";
			TEXT_REGISTER = "CREAR CUENTA";
			TEXT_FIELDS_NOT_FILLED = "RELLENA TODOS LOS CAMPOS";
			TEXT_MAX_LEN_PWD = "(Máx. 10 caracteres)";
			TEXT_SYS_CONFIRM_PWD = "Confirmar contraseña";
			TEXT_SYS_REGISTRATION  = "Panel de registro";
			TEXT_PWD_NOT_MATCHING = "LA CONTRASEÑA NO COINCIDE";
			TEXT_PWD_TOO_SHORT = "LA CONTRASEÑA DEBE TENER AL MENOS 3 CARACTERES";
			TEXT_PWD_TOO_LONG = "¡CONTRASEÑA MUY LARGA! MÁX. 10 CARACTERES";
			TEXT_EMAIL_NOT_VALID = "Inserte un correo electrónico válido";
			TEXT_ERR_USER_ALREADY_REGISTERED = "El nombre de usuario ya está registrado";
			TEXT_ERR_EMAIL_ALREADY_REGISTERED = "El correo electrónico ya está registrado";
			TEXT_GENERIC_REGISTER_ERR = "REGISTRO FALLIDO";
			TEXT_INVALID_PASSWORD = "CONTRASEÑA NO VÁLIDA";
			TEXT_PWD_FORGOT = "Olvidaste tu contraseña";
			TEXT_PWD_RECOVER = "Verifica tu correo electrónico para restablecer tu contraseña";
			TEXT_FIND_OPPONENTS = "Buscando oponente...";
			TEXT_GENERIC_LOGIN_FAILED = "¡Inicio de sesión fallido!";
			TEXT_INVALID_USER = "Nombre de usuario no encontrado";
			TEXT_YES = "Sí";
			TEXT_NO = "No";
			TEXT_DELETE_USER = "Eliminar usuario";
			
			TEXT_LEADERBOARD = "Tabla de Clasificación";
			TEXT_POSITION = "#";
			TEXT_RANK = "Rango";
			TEXT_NICKNAME = "Apodo";
			TEXT_POINTS = "Puntuación";
			TEXT_GENERAL_LEADERBOARD = "General";
			TEXT_MONTHLY_LEADERBOARD = "Mensual";
			TEXT_DAILY_LEADERBOARD = "Diario";
			
			TEXT_TERMS_OF_USE = "Términos de uso (EULA)";
			TEXT_PRIVACY = "Política de Privacidad";
			TEXT_TERMS_OF_USE_URL = "";
			TEXT_PRIVACY_URL = "https://codethislab.com/code-this-lab-srl-apps-privacy-policy-en/";
			TEXT_PERSONAL_DATA_MANAGEMENT = "Gestión de Datos Personales";
			TEXT_REMOVE_ADS = "Eliminar anuncios";
			TEXT_SVC_RESTORE = "Restaurar";
			break;
		}
		case LANG_FR:{
			TEXT_MY_PROFILE = "Mon Profil";
			TEXT_CREDITS_URL = "https://www.codethislab.com";
			TEXT_EDIT_PROFILE = "Modifier le Profil";
			TEXT_LOGOUT = "Déconnexion";
			TEXT_LOGIN = "Connexion";
			TEXT_SETTINGS = "Paramètres";
			TEXT_LANGUAGE = "Langue";
			TEXT_FULLSCREEN_OFF = "Mode Plein Écran Désactivé";
			TEXT_FULLSCREEN_ON = "Mode Plein Écran Activé";
			TEXT_MUSIC_OFF = "Audio Désactivé";
			TEXT_MUSIC_ON = "Audio Activé";
			TEXT_SFX_ON = "Sfx Activés";
			TEXT_SFX_OFF = "Sfx Désactivés";
			TEXT_ANIMATION_ON = "Animations Activées";
			TEXT_ANIMATION_OFF = "Animations Désactivées";
			TEXT_GAME_OPTION = "Option de Jeu";
			TEXT_MAIN_MENU = "Menu Principal";
			TEXT_SB_RESTART = "Redémarrer";
			TEXT_LEADERBOARD = "Classement";
			TEXT_ONLINE_ROOMS = "Salles en Ligne";
			TEXT_REPORT_BUG = "Signaler un Bug";
	
			TEXT_STATS = "Statistiques";
			TEXT_ARE_YOU_SURE = "ES-TU SÛR?";
			TEXT_MORE_GAMES = "Plus de Jeux";
			TEXT_MORE_GAMES_SUB = "Nouveaux Titres Gratuits";
			TEXT_MORE_GAMES_EXP = "VOUS VOULEZ JOUER PLUS DE JEUX ?\n\nCLIQUEZ SUR OK POUR CONSULTER NOTRE CATALOGUE";
			TEXT_CREDITS = "Crédits";
			TEXT_REGISTER = "S'Inscrire";
			TEXT_CLOSE = "Fermer";
			TEXT_EMAIL = "Adresse Email";
			TEXT_PWD = "Mot de Passe";
			TEXT_SUBMIT = "Soumettre";
			TEXT_NO_LEADERBOARD = "UCUN CLASSEMENT DISPONIBLE";
			TEXT_PLS_LOGIN = "VEUILLEZ VOUS CONNECTER POUR ACCÉDER À CETTE FONCTION";
			TEXT_FEATURED_GAMES = "Jeux Mis en Avant";
			TEXT_OTHER_GAMES = "Autres Jeux";
			TEXT_SEND_EMAIL = "Veuillez nous écrire à";
			TEXT_RANKING = "CLASSEMENT";
			TEXT_WINS = "VICTOIRES";
			TEXT_DEUCES = "MATCHS NULS";
			TEXT_LOSSES = "DÉFAITES";
			TEXT_WIN_PERC = "% DE VICTOIRES";
			TEXT_HELP_GAME_RULE = "Règles du jeu";
			
			TEXT_GUEST = "INVITÉ";
			
			TEXT_STATS_NO_LOGIN = "CONNECTEZ-VOUS POUR ENREGISTRER VOS PROGRÈS";
			TEXT_PLAY_GUEST = "JOUER EN TANT QU'INVITÉ";
			TEXT_LOGIN = "CONNEXION";
			TEXT_REGISTER = "CRÉATION DE COMPTE";
			TEXT_FIELDS_NOT_FILLED = "VEUILLEZ REMPLIR TOUS LES CHAMPS";
			TEXT_MAX_LEN_PWD = "(10 caractères max)";
			TEXT_SYS_CONFIRM_PWD = "Confirmer le mot de passe";
			TEXT_SYS_REGISTRATION  = "Inscription";
			TEXT_PWD_NOT_MATCHING = "LES MOTS DE PASSE NE CORRESPONDENT PAS";
			TEXT_PWD_TOO_SHORT = "LE MOT DE PASSE DOIT FAIRE AU MOINS 3 CARACTÈRES";
			TEXT_PWD_TOO_LONG = "MOT DE PASSE TROP LONG ! 10 CARACTÈRES MAX";
			TEXT_EMAIL_NOT_VALID = "Insérez une adresse e-mail valide";
			TEXT_ERR_USER_ALREADY_REGISTERED = "Le nom d'utilisateur est déjà enregistré";
			TEXT_ERR_EMAIL_ALREADY_REGISTERED = "L'e-mail est déjà enregistrée";
			TEXT_GENERIC_REGISTER_ERR = "INSCRIPTION ÉCHOUÉE";
			TEXT_INVALID_PASSWORD = "MOT DE PASSE NON VALIDE";
			TEXT_PWD_FORGOT = "Mot de passe oublié";
			TEXT_PWD_RECOVER = "Vérifiez votre e-mail pour réinitialiser votre mot de passe";
			TEXT_FIND_OPPONENTS = "Recherche d'adversaire...";
			TEXT_GENERIC_LOGIN_FAILED = "Connexion échouée!";
			TEXT_INVALID_USER = "Pseudo introuvable";
			TEXT_YES = "Oui";
			TEXT_NO = "Non";
			TEXT_DELETE_USER = "Supprimer l'utilisateur";
			
			TEXT_LEADERBOARD = "Classement";
			TEXT_POSITION = "#";
			TEXT_RANK = "Rang";
			TEXT_NICKNAME = "Pseudo";
			TEXT_POINTS = "Score";
			TEXT_GENERAL_LEADERBOARD = "Général";
			TEXT_MONTHLY_LEADERBOARD = "Mensuel";
			TEXT_DAILY_LEADERBOARD = "Quotidien";
			
			TEXT_TERMS_OF_USE = "Conditions d'utilisation (EULA)";
			TEXT_PRIVACY = "Politique de Confidentialité";
			TEXT_TERMS_OF_USE_URL = "";
			TEXT_PRIVACY_URL = "https://codethislab.com/code-this-lab-srl-apps-privacy-policy-en/";
			TEXT_PERSONAL_DATA_MANAGEMENT = "Gestion des Données Personnelles";
			TEXT_REMOVE_ADS = "Supprimer les publicités";
			TEXT_SVC_RESTORE = "Restaurer";
			break;
		}
		case LANG_DE:{
			TEXT_MY_PROFILE = "Mein Profil";
			TEXT_CREDITS_URL = "https://www.codethislab.com";
			TEXT_EDIT_PROFILE = "Profil Bearbeiten";
			TEXT_LOGOUT = "Abmelden";
			TEXT_LOGIN = "Anmelden";
			TEXT_SETTINGS = "Einstellungen";
			TEXT_LANGUAGE = "Sprache";
			TEXT_FULLSCREEN_OFF = "Vollbildmodus Aus";
			TEXT_FULLSCREEN_ON = "Vollbildmodus An";
			TEXT_MUSIC_OFF = "Audio Aus";
			TEXT_MUSIC_ON = "Audio An";
			TEXT_SFX_ON = "Sfx An";
			TEXT_SFX_OFF = "Sfx Aus";
			TEXT_ANIMATION_ON = "Animationen Ein";
			TEXT_ANIMATION_OFF = "Animationen Aus";
			TEXT_GAME_OPTION = "Spieleinstellung";
			TEXT_MAIN_MENU = "Hauptmenü";
			TEXT_SB_RESTART = "Neustart";
			TEXT_LEADERBOARD = "Bestenliste";
			TEXT_ONLINE_ROOMS = "Online-Räume";
			TEXT_REPORT_BUG = "Fehler Melden";

			TEXT_STATS = "Statistiken";
			TEXT_ARE_YOU_SURE = "BIST DU SICHER?";
			TEXT_MORE_GAMES = "Mehr Spiele";
			TEXT_MORE_GAMES_SUB = "Neue Kostenlose Titel";
			TEXT_MORE_GAMES_EXP = "MÖCHTEN SIE MEHR SPIELE SPIELEN?\n\nKLICKEN SIE AUF OK, UM UNSEREN KATALOG ZU SEHEN";
			TEXT_CREDITS = "Credits";
			
			TEXT_REGISTER = "Registrieren";
			TEXT_CLOSE = "Schließen";
			TEXT_EMAIL = "E-Mail-Adresse";
			TEXT_PWD = "Passwort";

			TEXT_SUBMIT = "Absenden";
			TEXT_NO_LEADERBOARD = "KEINE BESTENLISTE VERFÜGBAR";
			TEXT_PLS_LOGIN = "BITTE ANMELDEN, UM AUF DIESE FUNKTION ZUZUGREIFEN";
			TEXT_FEATURED_GAMES = "Ausgewählte Spiele";
			TEXT_OTHER_GAMES = "Andere Spiele";
			TEXT_SEND_EMAIL = "Bitte schreiben Sie uns unter";
			TEXT_RANKING = "RANG";
			TEXT_WINS = "SIEGE";
			TEXT_DEUCES = "UNENTSCHIEDEN";
			TEXT_LOSSES = "NIEDERLAGEN";
			TEXT_WIN_PERC = "SIEG-%";
			TEXT_HELP_GAME_RULE = "Spielregeln";
			
			TEXT_GUEST = "GAST";
			
			TEXT_STATS_NO_LOGIN = "EINLOGGEN, UM DEINE FORTSCHRITTE ZU SPEICHERN";
			TEXT_PLAY_GUEST = "ALS GAST SPIELEN";
			TEXT_LOGIN = "LOGIN";
			TEXT_REGISTER = "ACCOUNT ERSTELLEN";
			TEXT_FIELDS_NOT_FILLED = "BITTE FÜLLE ALLE FELDER AUS";
			TEXT_MAX_LEN_PWD = "(Max. 10 Zeichen)";
			TEXT_SYS_CONFIRM_PWD = "Passwort bestätigen";
			TEXT_SYS_REGISTRATION  = "Registrierungsfeld";
			TEXT_PWD_NOT_MATCHING = "PASSWORT STIMMT NICHT ÜBEREIN";
			TEXT_PWD_TOO_SHORT = "PASSWORT MUSS MINDESTENS 3 ZEICHEN LANG SEIN";
			TEXT_PWD_TOO_LONG = "PASSWORT ZU LANG! MAX. 10 ZEICHEN";
			TEXT_EMAIL_NOT_VALID = "Geben Sie eine gültige E-Mail-Adresse ein";
			TEXT_ERR_USER_ALREADY_REGISTERED = "Der Benutzername ist bereits registriert";
			TEXT_ERR_EMAIL_ALREADY_REGISTERED = "Die E-Mail ist bereits registriert";
			TEXT_GENERIC_REGISTER_ERR = "REGISTRIERUNG FEHLGESCHLAGEN";
			TEXT_INVALID_PASSWORD = "PASSWORT UNGÜLTIG";
			TEXT_PWD_FORGOT = "Passwort vergessen";
			TEXT_PWD_RECOVER = "Überprüfen Sie Ihre E-Mails, um Ihr Passwort zurückzusetzen";
			TEXT_FIND_OPPONENTS = "Gegner wird gesucht...";
			TEXT_GENERIC_LOGIN_FAILED = "Anmeldung fehlgeschlagen!";
			TEXT_INVALID_USER = "Benutzername nicht gefunden";
			TEXT_YES = "Ja";
			TEXT_NO = "NEIN";
			TEXT_DELETE_USER = "Benutzer löschen";
			
			TEXT_LEADERBOARD = "Bestenliste";
			TEXT_POSITION = "#";
			TEXT_RANK = "Rang";
			TEXT_NICKNAME = "Spitzname";
			TEXT_POINTS = "Punktzahl";
			TEXT_GENERAL_LEADERBOARD = "Allgemein";
			TEXT_MONTHLY_LEADERBOARD = "Monatlich";
			TEXT_DAILY_LEADERBOARD = "Täglich";
			
			TEXT_TERMS_OF_USE = "Nutzungsbedingungen (EULA)";
			TEXT_PRIVACY = "Datenschutzerklärung";
			TEXT_TERMS_OF_USE_URL = "";
			TEXT_PRIVACY_URL = "https://codethislab.com/code-this-lab-srl-apps-privacy-policy-en/";
			TEXT_PERSONAL_DATA_MANAGEMENT = "Verwaltung personenbezogener Daten";
			TEXT_REMOVE_ADS = "Werbung entfernen";
			TEXT_SVC_RESTORE = "Wiederherstellen";
			break;
		}
		case LANG_PT:{
			TEXT_MY_PROFILE = "Meu Perfil";
			TEXT_CREDITS_URL = "https://www.codethislab.com";
			TEXT_EDIT_PROFILE = "Editar Perfil";
			TEXT_LOGOUT = "Sair";
			TEXT_LOGIN = "Entrar";
			TEXT_SETTINGS = "Configurações";
			TEXT_LANGUAGE = "Idioma";
			TEXT_FULLSCREEN_OFF = "Modo Tela Cheia Desativado";
			TEXT_FULLSCREEN_ON = "Modo Tela Cheia Ativado";
			TEXT_MUSIC_OFF = "Áudio Desativado";
			TEXT_MUSIC_ON = "Áudio Ativado";
			TEXT_SFX_ON = "Sfx Ligado";
			TEXT_SFX_OFF = "Sfx Desligado";
			TEXT_ANIMATION_ON = "Animações Ativadas";
			TEXT_ANIMATION_OFF = "Animações Desativadas";
			TEXT_GAME_OPTION = "Opção de Jogo";
			TEXT_MAIN_MENU = "Menu Principal";
			TEXT_SB_RESTART = "Reiniciar";
			TEXT_LEADERBOARD = "Tabela de Classificação";
			TEXT_ONLINE_ROOMS = "Salas Online";
			TEXT_REPORT_BUG = "Relatar um Bug";
		
			TEXT_STATS = "Estatísticas";
			TEXT_ARE_YOU_SURE = "TENS A CERTEZA?";
			TEXT_MORE_GAMES = "Mais Jogos";
			TEXT_MORE_GAMES_SUB = "Novos Títulos Gratuitos";
			TEXT_MORE_GAMES_EXP = "VOCÊ QUER JOGAR MAIS JOGOS?\n\nCLIQUE EM OK PARA VER NOSSO CATÁLOGO";
			TEXT_CREDITS = "Créditos";
			
			TEXT_REGISTER = "Registrar-se";
			TEXT_CLOSE = "Fechar";
			TEXT_EMAIL = "Endereço de Email";
			TEXT_PWD = "Senha";

			TEXT_SUBMIT = "Enviar";
			TEXT_NO_LEADERBOARD = "NÃO HÁ TABELA DE CLASSIFICAÇÃO DISPONÍVEL";
			TEXT_PLS_LOGIN = "POR FAVOR, FAÇA LOGIN PARA ACESSAR ESTA FUNÇÃO";
			TEXT_FEATURED_GAMES = "Jogos em Destaque";
			TEXT_OTHER_GAMES = "Outros Jogos";
			TEXT_SEND_EMAIL = "Por favor, escreva-nos em";
			TEXT_RANKING = "CLASSIFICAÇÃO";
			TEXT_WINS = "VITÓRIAS";
			TEXT_DEUCES = "EMPATES";
			TEXT_LOSSES = "DERROTAS";
			TEXT_WIN_PERC = "% de VITÓRIAS";
			TEXT_HELP_GAME_RULE = "Regras do jogo";
			
			TEXT_GUEST = "CONVIDADO";
			
			TEXT_STATS_NO_LOGIN = "FAÇA LOGIN PARA SALVAR SEUS PROGRESSOS";
			TEXT_PLAY_GUEST = "JOGAR COMO CONVIDADO";
			TEXT_LOGIN = "INÍCIO DE SESSÃO";
			TEXT_REGISTER = "CRIAR CONTA";
			TEXT_FIELDS_NOT_FILLED = "PREENCHE TODOS OS CAMPOS";
			TEXT_MAX_LEN_PWD = "(Máximo de 10 caracteres)";
			TEXT_SYS_CONFIRM_PWD = "Confirmar palavra-passe";
			TEXT_SYS_REGISTRATION  = "Painel de registo";
			TEXT_PWD_NOT_MATCHING = "A PALAVRA-PASSE NÃO CORRESPONDE";
			TEXT_PWD_TOO_SHORT = "A PALAVRA-PASSE TEM DE TER 3 CARACTERES";
			TEXT_PWD_TOO_LONG = "PALAVRA-PASSE LONGA DEMAIS! MÁXIMO DE 10 CARACTERES";
			TEXT_EMAIL_NOT_VALID = "Insira um e-mail válido";
			TEXT_ERR_USER_ALREADY_REGISTERED = "O nome de usuário já está registrado";
			TEXT_ERR_EMAIL_ALREADY_REGISTERED = "O e-mail já está registrado";
			TEXT_GENERIC_REGISTER_ERR = "REGISTO FALHADO";
			TEXT_INVALID_PASSWORD = "SENHA INVÁLIDA";
			TEXT_PWD_FORGOT = "Esqueceu a senha";
			TEXT_PWD_RECOVER = "Verifique seu e-mail para redefinir sua senha";
			TEXT_FIND_OPPONENTS = "Procurando oponente...";
			TEXT_GENERIC_LOGIN_FAILED = "Falha no login!";
			TEXT_INVALID_USER = "Apelido não encontrado";
			TEXT_YES = "Sim";
			TEXT_NO = "Não";
			TEXT_DELETE_USER = "Excluir usuário";
			
			TEXT_LEADERBOARD = "Tabela de Classificação";
			TEXT_POSITION = "#";
			TEXT_RANK = "Classificação";
			TEXT_NICKNAME = "Apelido";
			TEXT_POINTS = "Pontuação";
			TEXT_GENERAL_LEADERBOARD = "Geral";
			TEXT_MONTHLY_LEADERBOARD = "Mensal";
			TEXT_DAILY_LEADERBOARD = "Diário";
			
			TEXT_TERMS_OF_USE = "Termos de Uso (EULA)";
			TEXT_PRIVACY = "Política de Privacidade";
			TEXT_TERMS_OF_USE_URL = "";
			TEXT_PRIVACY_URL = "https://codethislab.com/code-this-lab-srl-apps-privacy-policy-en/";
			TEXT_PERSONAL_DATA_MANAGEMENT = "Gestão de Dados Pessoais";
			TEXT_REMOVE_ADS = "Remover anúncios";
			TEXT_SVC_RESTORE = "Restaurar";
			break;
		}
		case LANG_IT:{
			TEXT_MY_PROFILE = "Il Mio Profilo";
			TEXT_CREDITS_URL = "https://www.codethislab.it";
			TEXT_EDIT_PROFILE = "Modifica Profilo";
			TEXT_LOGOUT = "Esci";
			TEXT_LOGIN = "Accedi";
			TEXT_SETTINGS = "Impostazioni";
			TEXT_LANGUAGE = "Lingua";
			TEXT_FULLSCREEN_OFF = "Modalità Schermo Intero Disattivata";
			TEXT_FULLSCREEN_ON = "Modalità Schermo Intero Attivata";
			TEXT_MUSIC_OFF = "Audio Disattivo";
			TEXT_MUSIC_ON = "Audio Attivo";
			TEXT_SFX_ON = "Sfx Attivo";
			TEXT_SFX_OFF = "Sfx Disattivo";
			TEXT_ANIMATION_ON = "Animazioni Attive";
			TEXT_ANIMATION_OFF = "Animazioni Disattive";
			TEXT_GAME_OPTION = "Opzioni di Gioco";
			TEXT_MAIN_MENU = "Menu Principale";
			TEXT_SB_RESTART = "Ricomincia";
			TEXT_LEADERBOARD = "Classifica";
			TEXT_ONLINE_ROOMS = "Stanze Online";
			TEXT_REPORT_BUG = "Segnala un Bug";

			TEXT_STATS = "Statistiche";
			TEXT_ARE_YOU_SURE = "SEI SICURO?";
			TEXT_MORE_GAMES = "Altri Giochi";
			TEXT_MORE_GAMES_SUB = "Nuovi Titoli Gratuiti";
			TEXT_MORE_GAMES_EXP = "VUOI GIOCARE A PIÙ GIOCHI?\n\nCLICCA OK PER GUARDARE IL NOSTRO CATALOGO";
			TEXT_CREDITS = "Crediti";
			
			TEXT_REGISTER = "Registrati";
			TEXT_CLOSE = "Chiudi";
			TEXT_EMAIL = "Indirizzo Email";
			TEXT_PWD = "Password";
	
			TEXT_SUBMIT = "Invia";
			TEXT_NO_LEADERBOARD = "Nessuna Classifica Disponibile";
			TEXT_PLS_LOGIN = "Effettua il Login per accedere a questa funzione";
			TEXT_FEATURED_GAMES = "Giochi in Primo Piano";
			TEXT_OTHER_GAMES = "Altri Giochi";
			TEXT_SEND_EMAIL = "Per favore scrivici a";
			TEXT_RANKING = "RANKING";
			TEXT_WINS = "VITTORIE";
			TEXT_DEUCES = "PAREGGI";
			TEXT_LOSSES = "SCONFITTE";
			TEXT_WIN_PERC = "PERCENTUALE DI VITTORIE %";
			TEXT_HELP_GAME_RULE = "Regole di Gioco";

			TEXT_GUEST = "OSPITE";
			
			TEXT_STATS_NO_LOGIN = "EFFETTUA L'ACCESSO PER SALVARE I TUOI PROGRESSI";
			TEXT_PLAY_GUEST = "GIOCARE COME OSPITE";
			TEXT_LOGIN = "LOGIN";
			TEXT_REGISTER = "CREA ACCOUNT";
			TEXT_FIELDS_NOT_FILLED = "RIEMPI TUTTI I CAMPI PER FAVORE";
			TEXT_MAX_LEN_PWD = "(Max 10 caratteri)";
			TEXT_SYS_CONFIRM_PWD = "Conferma Password";
			TEXT_SYS_REGISTRATION  = "Pannello di Registrazione";
			TEXT_PWD_NOT_MATCHING = "LA PASSWORD NON COINCIDE";
			TEXT_PWD_TOO_SHORT = "LA PASSWORD DEVE CONTENERE ALMENO 3 CARATTERI";
			TEXT_PWD_TOO_LONG = "PASSWORD TROPPO LUNGA! MAX 10 CARATTERI";
			TEXT_EMAIL_NOT_VALID = "Inserisci un'email valida";
			TEXT_ERR_USER_ALREADY_REGISTERED = "Il nome utente è già registrato";
			TEXT_ERR_EMAIL_ALREADY_REGISTERED = "La email è già registrata";
			TEXT_GENERIC_REGISTER_ERR = "REGISTRAZIONE FALLITA";
			TEXT_INVALID_PASSWORD = "PASSWORD NON VALIDA";
			TEXT_PWD_FORGOT = "Hai dimenticato la password?";
			TEXT_PWD_RECOVER = "Controlla la tua email per reimpostare la password";
			TEXT_FIND_OPPONENTS = "Ricerca avversario...";
			TEXT_GENERIC_LOGIN_FAILED = "Accesso fallito!";
			TEXT_INVALID_USER = "Nickname non trovato";
			TEXT_YES = "Sì";
			TEXT_NO = "No";
			TEXT_DELETE_USER = "Cancella Utente";
			
			TEXT_LEADERBOARD = "Classifica";
			TEXT_POSITION = "#";
			TEXT_RANK = "Grado";
			TEXT_NICKNAME = "Nickname";
			TEXT_POINTS = "Punti";
			TEXT_GENERAL_LEADERBOARD = "Generale";
			TEXT_MONTHLY_LEADERBOARD = "Mensile";
			TEXT_DAILY_LEADERBOARD = "Giornaliero";
			
			TEXT_TERMS_OF_USE = "Termini e Condizioni (EULA)";
			TEXT_PRIVACY = "Informativa sulla Privacy";
			TEXT_TERMS_OF_USE_URL = "";
			TEXT_PRIVACY_URL = "https://codethislab.com/code-this-lab-srl-apps-privacy-policy-en/";
			TEXT_PERSONAL_DATA_MANAGEMENT = "Gestione dei Dati Personali";
			TEXT_REMOVE_ADS = "Rimuovi pubblicità";
			TEXT_SVC_RESTORE = "Ripristina";
			break;
		}
		case LANG_TR:{
			TEXT_MY_PROFILE = "Profilim";
			TEXT_CREDITS_URL = "https://www.codethislab.com";
			TEXT_EDIT_PROFILE = "Profili Düzenle";
			TEXT_LOGOUT = "Çıkış Yap";
			TEXT_LOGIN = "Giriş Yap";
			TEXT_SETTINGS = "Ayarlar";
			TEXT_LANGUAGE = "Dil";
			TEXT_FULLSCREEN_OFF = "Tam Ekran Modu Kapali";
			TEXT_FULLSCREEN_ON = "am Ekran Modu Açik";
			TEXT_MUSIC_OFF = "Ses Kapali";
			TEXT_MUSIC_ON = "Ses Açik";
			TEXT_SFX_ON = "Ses Efektleri Açık"; 
			TEXT_SFX_OFF = "Ses Efektleri Kapalı";
			TEXT_ANIMATION_ON = "Animasyonlar Açık";
			TEXT_ANIMATION_OFF = "Animasyonlar Kapalı";
			TEXT_GAME_OPTION = "Oyun Seçenekleri";
			TEXT_MAIN_MENU = "Ana Menü";
			TEXT_SB_RESTART = "Yeniden Başlat";
			TEXT_LEADERBOARD = "Liderlik Tablosu";
			TEXT_ONLINE_ROOMS = "Çevrimiçi Odalar";
			TEXT_REPORT_BUG = "Hata Bildir";

			TEXT_STATS = "İstatistikler";
			TEXT_ARE_YOU_SURE = "EMİN MİSİN?";
			TEXT_MORE_GAMES = "Daha Fazla Oyun";
			TEXT_MORE_GAMES_SUB = "Yeni Ücretsiz Başlıklar";
			TEXT_MORE_GAMES_EXP = "DAHA FAZLA OYUN OYNAMAK İSTER MİSİNİZ?\n\nKATALOĞUMUZU İZLEMEK İÇİN TAMAM'I TIKLAYIN";
			TEXT_CREDITS = "Krediler";
			
			TEXT_REGISTER = "Kayıt Ol";
			TEXT_CLOSE = "Kapat";
			TEXT_EMAIL = "E-posta Adresi";
			TEXT_PWD = "Şifre";
	
			TEXT_SUBMIT = "Gönder";
			TEXT_NO_LEADERBOARD = "LİDER TABLOSU YOK";
			TEXT_PLS_LOGIN = "LÜTFEN BU ÖZELLİĞE ERİŞMEK İÇİN GİRİŞ YAPIN";
			TEXT_FEATURED_GAMES = "Öne Çıkan Oyunlar";
			TEXT_OTHER_GAMES = "Diğer Oyunlar";
			TEXT_SEND_EMAIL = "Lütfen bize şuradan yazın";
			TEXT_RANKING = "SIRALAMA";
			TEXT_WINS = "GALİBİYET";
			TEXT_DEUCES = "BERABERLİKLER";
			TEXT_LOSSES = "KAYBETMELER";
			TEXT_WIN_PERC = "KAZANMA%";
			TEXT_HELP_GAME_RULE = "Oyun Kuralları";
			
			TEXT_GUEST = "MİSAFİR";
			
			TEXT_STATS_NO_LOGIN = " İLERLEMELERİNİZİ KAYDETMEK İÇİN GİRİŞ YAPIN";
			TEXT_PLAY_GUEST = "MISAFİR OLARAK OYNA";
			TEXT_LOGIN = "Oturum açma";
			TEXT_REGISTER = "HESAP OLUŞTUR";
			TEXT_FIELDS_NOT_FILLED = "LÜTFEN TÜM ALANLARI DOLDUR";
			TEXT_MAX_LEN_PWD = "(En fazla 10 karakter)";
			TEXT_SYS_CONFIRM_PWD = "Şifreyi Onayla";
			TEXT_SYS_REGISTRATION  = "Kayıt Paneli";
			TEXT_PWD_NOT_MATCHING = "ŞİFRE EŞLEŞMİYOR";
			TEXT_PWD_TOO_SHORT = "ŞİFRE EN AZ 3 KARAKTER UZUNLUĞUNDA OLMALIDIR";
			TEXT_PWD_TOO_LONG = "ŞİFRE FAZLA UZUN! EN FAZLA 10 KARAKTER";
			TEXT_EMAIL_NOT_VALID = "Geçerli bir e-posta girin";
			TEXT_ERR_USER_ALREADY_REGISTERED = "Kullanıcı adı zaten kayıtlı";
			TEXT_ERR_EMAIL_ALREADY_REGISTERED = "E-posta zaten kayıtlı";
			TEXT_GENERIC_REGISTER_ERR = "KAYIT BAŞARISIZ";
			TEXT_INVALID_PASSWORD = "GEÇERSİZ ŞİFRE";
			TEXT_PWD_FORGOT = "Şifremi unuttum";
			TEXT_PWD_RECOVER = "Şifrenizi sıfırlamak için e-postanızı kontrol edin";
			TEXT_FIND_OPPONENTS = "Rakip aranıyor...";
			TEXT_GENERIC_LOGIN_FAILED = "Giriş başarısız!";
			TEXT_INVALID_USER = "Takma ad bulunamadı";
			TEXT_YES = "Evet";
			TEXT_NO = "HAYIR";
			TEXT_DELETE_USER = "Kullanıcıyı sil";
			
			TEXT_LEADERBOARD = "Liderlik Tablosu";
			TEXT_POSITION = "#";
			TEXT_RANK = "Sıra";
			TEXT_NICKNAME = "Takma ad";
			TEXT_POINTS = "Skor";
			TEXT_GENERAL_LEADERBOARD = "Genel";
			TEXT_MONTHLY_LEADERBOARD = "Aylık";
			TEXT_DAILY_LEADERBOARD = "Günlük";
			
			TEXT_TERMS_OF_USE = "Kullanım Koşulları (EULA)";
			TEXT_PRIVACY = "Gizlilik Politikası";
			TEXT_TERMS_OF_USE_URL = "";
			TEXT_PRIVACY_URL = "https://codethislab.com/code-this-lab-srl-apps-privacy-policy-en/";
			TEXT_PERSONAL_DATA_MANAGEMENT = "Kişisel Veri Yönetimi";
			TEXT_REMOVE_ADS = "Reklamları kaldır";
			TEXT_SVC_RESTORE = "Geri yükleme";
			break;
		}
		case LANG_AR:{
			TEXT_MY_PROFILE = "ملفّي";
			TEXT_CREDITS_URL = "https://www.codethislab.com";
			TEXT_EDIT_PROFILE = "تحرير الملف الشخصي ";
			TEXT_LOGOUT = "تسجيل الخروج";
			TEXT_LOGIN = "تسجيل الدخول";
			TEXT_SETTINGS = "الإعدادات";
			TEXT_LANGUAGE = "اللغة";
			TEXT_FULLSCREEN_OFF = "وضع الشاشة الكاملة معطل";
			TEXT_FULLSCREEN_ON = "وضع الشاشة الكاملة مفعل";
			TEXT_MUSIC_OFF = "الصوت معطل";
			TEXT_MUSIC_ON = "الصوت مفعل";
			TEXT_SFX_ON = "المؤثرات الصوتية مفعلة"; 
			TEXT_SFX_OFF = "المؤثرات الصوتية معطلة";
			TEXT_ANIMATION_ON = "تشغيل الرسوم المتحركة";
			TEXT_ANIMATION_OFF = "إيقاف الرسوم المتحركة";
			TEXT_GAME_OPTION = "خيار اللعبة";
			TEXT_MAIN_MENU = "القائمة الرئيسية";
			TEXT_SB_RESTART = "إِعَادَةُ التَّشْغِيلِ";
			TEXT_LEADERBOARD = "لائحة الرتب";
			TEXT_ONLINE_ROOMS = "غرف الإنترنت";
			TEXT_REPORT_BUG = "الإبلاغ عن خطأ";

			TEXT_STATS = "إحصائيات";
			TEXT_ARE_YOU_SURE = "هل أنت متأكد؟";
			TEXT_MORE_GAMES = "المزيد من الألعاب";
			TEXT_MORE_GAMES_SUB = "عناوين مجانية جديدة";
			TEXT_MORE_GAMES_EXP = "هل تريد تشغيل المزيد من الألعاب؟ \n \n انقر فوق موافق لمشاهدة كتالوجنا";
			TEXT_CREDITS = "اعتمادات";
			
			TEXT_REGISTER = "تسجيل";
			TEXT_CLOSE = "إغلاق";
			TEXT_EMAIL = "عنوان البريد الإلكتروني";
			TEXT_PWD = "كلمة المرور";
		
			TEXT_SUBMIT = "إرسال";
			TEXT_NO_LEADERBOARD = "لا يوجد لائحة رتب متاحة";
			TEXT_PLS_LOGIN = "يرجى تسجيل الدخول للوصول إلى هذه الميزة";
			TEXT_FEATURED_GAMES = "ألعاب مميزة";
			TEXT_OTHER_GAMES = "ألعاب أخرى";
			TEXT_SEND_EMAIL = "يرجى الكتابة إلينا على";
			TEXT_RANKING = "الترتيب";
			TEXT_WINS = "فوز";
			TEXT_DEUCES = "التعادلات";
			TEXT_LOSSES = "الهزائم";
			TEXT_WIN_PERC = "الانتصار%";
			TEXT_HELP_GAME_RULE = "قواعد اللعبة";
			
			TEXT_GUEST = "ضيف";
			
			TEXT_STATS_NO_LOGIN = "سجّل الدخول لحفظ تقدماتك";
			TEXT_PLAY_GUEST = "اللعب كضيف";
			TEXT_LOGIN = "تسجيل دخول";
			TEXT_REGISTER = "إنشاء حساب";
			TEXT_FIELDS_NOT_FILLED = "يُرجى ملء جميع الحقول";
			TEXT_MAX_LEN_PWD = "(الحد الأقصى 10 رموز)";
			TEXT_SYS_CONFIRM_PWD = "تأكيد كلمة المرور";
			TEXT_SYS_REGISTRATION  = "لوحة التسجيل";
			TEXT_PWD_NOT_MATCHING = "كلمة المرور ليست متطابقة";
			TEXT_PWD_TOO_SHORT = "يجب أن يكون طول كلمة المرور 3 رموز على الأقل";
			TEXT_PWD_TOO_LONG = "كلمة المرور طويلة للغاية الحد الأقصى 10 رموز";
			TEXT_EMAIL_NOT_VALID = "الرجاء إدخال عنوان بريد إلكتروني صالح";
			TEXT_ERR_USER_ALREADY_REGISTERED = "اسم المستخدم مُسجّل بالفعل";
			TEXT_ERR_EMAIL_ALREADY_REGISTERED = "البريد الإلكتروني مسجل بالفعل";
			TEXT_GENERIC_REGISTER_ERR = "فشل التسجيل";
			TEXT_INVALID_PASSWORD = "كلمة المرور غير صالحة";
			TEXT_PWD_FORGOT = "نسيت كلمة المرور";
			TEXT_PWD_RECOVER = "تحقق من بريدك الإلكتروني لإعادة تعيين كلمة المرور";
			TEXT_FIND_OPPONENTS = "البحث عن الخصم...";
			TEXT_GENERIC_LOGIN_FAILED = "فشل تسجيل الدخول!";
			TEXT_INVALID_USER = "الاسم المستعار غير موجود";
			TEXT_YES = "نعم";
			TEXT_NO = "لا";
			TEXT_DELETE_USER = "حذف المستخدم";
			
			TEXT_LEADERBOARD = " لوحة المتصدرين";
			TEXT_POSITION = "#";
			TEXT_RANK = "ترتيب";
			TEXT_NICKNAME = "اسم مستعار";
			TEXT_POINTS = "النتيجة";
			TEXT_GENERAL_LEADERBOARD = "عام";
			TEXT_MONTHLY_LEADERBOARD = "شهرياً";
			TEXT_DAILY_LEADERBOARD = "يومي";
			
			TEXT_TERMS_OF_USE = "شروط الاستخدام (EULA)";
			TEXT_PRIVACY = "سياسة الخصوصية" ;
			TEXT_TERMS_OF_USE_URL = "";
			TEXT_PRIVACY_URL = "https://codethislab.com/code-this-lab-srl-apps-privacy-policy-en/";
			TEXT_PERSONAL_DATA_MANAGEMENT = "إدارة البيانات الشخصية";
			TEXT_REMOVE_ADS = "إزالة الإعلانات";
			TEXT_SVC_RESTORE = "يعيد";
			break;
		}
		case LANG_HI:{
			TEXT_MY_PROFILE = "मेरी प्रोफ़ाइल";
			TEXT_CREDITS_URL = "https://www.codethislab.com";
			TEXT_EDIT_PROFILE = "प्रोफ़ाइल संपादित करें";
			TEXT_LOGOUT = "लॉग आउट करें";
			TEXT_LOGIN = "लॉगिन करें ";
			TEXT_SETTINGS = "सेटिंग्स";
			TEXT_LANGUAGE = "भाषा";
			TEXT_FULLSCREEN_OFF = "पूर्ण स्क्रीन मोड बंद";
			TEXT_FULLSCREEN_ON = "पूर्ण स्क्रीन मोड चालू";
			TEXT_MUSIC_OFF = "ऑडियो बंद";
			TEXT_MUSIC_ON = "ऑडियो चालू";
			TEXT_SFX_ON = "ध्वनि प्रभाव चालू"; 
			TEXT_SFX_OFF = "ध्वनि प्रभाव बंद";
			TEXT_ANIMATION_ON = "एनिमेशन चालू";
			TEXT_ANIMATION_OFF = "एनिमेशन बंद";
			TEXT_GAME_OPTION = "खेल विकल्प";
			TEXT_MAIN_MENU = "मुख्य मेनू ";
			TEXT_SB_RESTART = "पुनः प्रारंभ करें";
			TEXT_LEADERBOARD = "लीडरबोर्ड ";
			TEXT_ONLINE_ROOMS = "ऑनलाइन कमरे";
			TEXT_REPORT_BUG = "बग की रिपोर्ट करें";

			TEXT_STATS = "सांख्यिकी";
			TEXT_ARE_YOU_SURE = "क्या आप सुनिश्चित हैं?";
			TEXT_MORE_GAMES = "अधिक खेल";
			TEXT_MORE_GAMES_SUB = "नए मुफ्त शीर्षक";
			TEXT_MORE_GAMES_EXP = "क्या आप और गेम खेलना चाहते हैं?\n\nहमारी सूची देखने के लिए ठीक क्लिक करें";
			TEXT_CREDITS = "क्रेडिट्स";
			
			TEXT_REGISTER = "रजिस्टर ";
			TEXT_CLOSE = "बंद करें";
			TEXT_EMAIL = "ईमेल पता";
			TEXT_PWD = "पासवर्ड ";
		
			TEXT_SUBMIT = "प्रस्तुत";
			TEXT_NO_LEADERBOARD = "कोई लीडरबोर्ड उपलब्ध नहीं है";
			TEXT_PLS_LOGIN = "कृपया इस सुविधा का उपयोग करने के लिए लॉगिन करें";
			TEXT_FEATURED_GAMES = "विशेष खेल";
			TEXT_OTHER_GAMES = "अन्य खेल";
			TEXT_SEND_EMAIL = "कृपया हमें इस पते पर लिखें";
			TEXT_RANKING = "रैंकिंग";
			TEXT_WINS = "जीत";
			TEXT_DEUCES = "ड्यूस";
			TEXT_LOSSES = "हार";
			TEXT_WIN_PERC = "जीत%";
			TEXT_HELP_GAME_RULE = "खेल के नियम";
			
			TEXT_GUEST = "अतिथि";
			
			TEXT_STATS_NO_LOGIN = " प्रगति को सहेजने के लिए लॉगिन करें";
			TEXT_PLAY_GUEST = "मेहमान के रूप में खेलें";
			TEXT_LOGIN = "लॉगइन";
			TEXT_REGISTER = "अकाउंट बनाएं";
			TEXT_FIELDS_NOT_FILLED = "कृपया सभी फ़ील्ड भरें";
			TEXT_MAX_LEN_PWD = "(अधिकतम 10 अक्षर)";
			TEXT_SYS_CONFIRM_PWD = "पासवर्ड की पुष्टि करें";
			TEXT_SYS_REGISTRATION  = "पंजीकरण पैनल";
			TEXT_PWD_NOT_MATCHING = "पासवर्ड मेल नहीं खा रहा है";
			TEXT_PWD_TOO_SHORT = "पासवर्ड कम से कम 3 अक्षरों का होना चाहिए";
			TEXT_PWD_TOO_LONG = "पासवर्ड बहुत लंबा है! अधिकतम 10 अक्षर";
			TEXT_EMAIL_NOT_VALID = "मान्य ई-मेल डालें";
			TEXT_ERR_USER_ALREADY_REGISTERED = "उपयोगकर्ता नाम पहले से ही पंजीकृत है";
			TEXT_ERR_EMAIL_ALREADY_REGISTERED = "ईमेल पहले से ही पंजीकृत है";
			TEXT_GENERIC_REGISTER_ERR = "पंजीकरण असफल हुआ";
			TEXT_INVALID_PASSWORD = "अमान्य पासवर्ड";
			TEXT_PWD_FORGOT = "पासवर्ड भूल गए";
			TEXT_PWD_RECOVER = "अपना पासवर्ड रीसेट करने के लिए अपने ईमेल की जांच करें";
			TEXT_FIND_OPPONENTS = "प्रतिद्वंदी की खोज...";
			TEXT_GENERIC_LOGIN_FAILED = "लॉगिन असफल!";
			TEXT_INVALID_USER = "उपनाम नहीं मिला";
			TEXT_YES = "हाँ";
			TEXT_NO = "नहीं";
			TEXT_DELETE_USER = "उपयोगकर्ता हटाएं";
			
			TEXT_LEADERBOARD = "लीडरबोर्ड";
			TEXT_POSITION ="#";
			TEXT_RANK = "रैंक";
			TEXT_NICKNAME = "उपनाम";
			TEXT_POINTS = "स्कोर";
			TEXT_GENERAL_LEADERBOARD = "सामान्य";
			TEXT_MONTHLY_LEADERBOARD = "मासिक";
			TEXT_DAILY_LEADERBOARD = "दैनिक ";
			
			TEXT_TERMS_OF_USE = "उपयोग की शर्तें (EULA)";
			TEXT_PRIVACY = "गोपनीयता नीति";
			TEXT_TERMS_OF_USE_URL = "";
			TEXT_PRIVACY_URL = "https://codethislab.com/code-this-lab-srl-apps-privacy-policy-en/";
			TEXT_PERSONAL_DATA_MANAGEMENT = "व्यक्तिगत डेटा प्रबंधन";
			TEXT_REMOVE_ADS = "विज्ञापन हटाएँ";
			TEXT_SVC_RESTORE = "रीस्टोर करें";
			break;
		}
		case LANG_ID:{
			TEXT_MY_PROFILE = "Profil Saya";
			TEXT_CREDITS_URL = "https://www.codethislab.com";
			TEXT_EDIT_PROFILE = "Edit Profil";
			TEXT_LOGOUT = "Keluar";
			TEXT_LOGIN = "Masuk";
			TEXT_SETTINGS = "Pengaturan";
			TEXT_LANGUAGE = "Bahasa";
			TEXT_FULLSCREEN_OFF = "Mode Layar Penuh Mati";
			TEXT_FULLSCREEN_ON = "Mode Layar Penuh Hidup";
			TEXT_MUSIC_OFF = "Audio Mati";
			TEXT_MUSIC_ON = "Audio Hidup";
			TEXT_SFX_ON = "Efek Suara Aktif"; 
			TEXT_SFX_OFF = "Efek Suara Mati";
			TEXT_ANIMATION_ON = "Animasi Aktif";
			TEXT_ANIMATION_OFF = "Animasi Nonaktif";
			TEXT_GAME_OPTION = "Opsi Permainan";
			TEXT_MAIN_MENU = "Menu Utama";
			TEXT_SB_RESTART = "Mulai Ulang";
			TEXT_LEADERBOARD = "Papan Pemimpin";
			TEXT_ONLINE_ROOMS = "Ruang Online";
			TEXT_REPORT_BUG = "Laporkan Bug";

			TEXT_STATS = "Statistik";
			TEXT_ARE_YOU_SURE = "KAMU YAKIN?";
			TEXT_MORE_GAMES = "Lebih Banyak Permainan";
			TEXT_MORE_GAMES_SUB = "Judul Gratis Baru";
			TEXT_MORE_GAMES_EXP = "APAKAH ANDA INGIN BERMAIN GAME LAINNYA?\n\nKLIK Oke UNTUK MENONTON KATALOG KAMI";
			TEXT_CREDITS = "Kredit";
		
			TEXT_REGISTER = "Daftar";
			TEXT_CLOSE = "Tutup";
			TEXT_EMAIL = "Alamat Email";
			TEXT_PWD = "Kata Sandi";
			
			TEXT_SUBMIT = "Kirim";
			TEXT_NO_LEADERBOARD = "TIDAK ADA PAPAN PEMIMPIN TERSEDIA";
			TEXT_PLS_LOGIN = "SILAKAN MASUK UNTUK MENGAKSES FITUR INI";
			TEXT_FEATURED_GAMES = "Permainan Unggulan";
			TEXT_OTHER_GAMES = "Permainan Lainnya";
			TEXT_SEND_EMAIL = "Silakan tulis kami di";
			TEXT_RANKING = "PERINGKAT";
			TEXT_WINS = "KEMENANGAN";
			TEXT_DEUCES = "SERI";
			TEXT_LOSSES = "KALAH";
			TEXT_WIN_PERC = "MENANG%";
			TEXT_HELP_GAME_RULE = "Aturan Permainan";
			
			TEXT_GUEST = "TAMU";
			
			TEXT_STATS_NO_LOGIN = "MASUK UNTUK MENYIMPAN KEMAJUAN ANDA";
			TEXT_PLAY_GUEST = "BERMAIN SEBAGAI TAMU";
			TEXT_LOGIN = "Log masuk";
			TEXT_REGISTER = "BUAT AKUN";
			TEXT_FIELDS_NOT_FILLED = "ISI SEMUA BIDANG";
			TEXT_MAX_LEN_PWD = "(Maks. 10 karakter)";
			TEXT_SYS_CONFIRM_PWD = "Konfirmasi Kata Sandi";
			TEXT_SYS_REGISTRATION  = "Panel Registrasi";
			TEXT_PWD_NOT_MATCHING = "KATA SANDI TIDAK SESUAI";
			TEXT_PWD_TOO_SHORT = "PANJANG KATA SANDI MIN. 3 KARAKTER";
			TEXT_PWD_TOO_LONG = "KATA SANDI TERLALU PANJANG! MAKS. 10 KARAKTER";
			TEXT_EMAIL_NOT_VALID = "Masukkan surel yang valid";
			TEXT_ERR_USER_ALREADY_REGISTERED = "Nama pengguna sudah terdaftar";
			TEXT_ERR_EMAIL_ALREADY_REGISTERED = "Email sudah terdaftar";
			TEXT_GENERIC_REGISTER_ERR = "PENDAFTARAN GAGAL";
			TEXT_INVALID_PASSWORD = "KATA SANDI TIDAK VALID";
			TEXT_PWD_FORGOT = "Lupa kata sandi";
			TEXT_PWD_RECOVER = "Periksa email Anda untuk mengatur ulang kata sandi Anda";
			TEXT_FIND_OPPONENTS = "Mencari lawan...";
			TEXT_GENERIC_LOGIN_FAILED = "Login gagal!";
			TEXT_INVALID_USER = "Nama panggilan tidak ditemukan";
			TEXT_YES = "Ya";
			TEXT_NO = "TIDAK";
			TEXT_DELETE_USER = "Hapus pengguna";
			
			TEXT_LEADERBOARD = "Papan Peringkat";
			TEXT_POSITION = "#";
			TEXT_RANK = "Peringkat";
			TEXT_NICKNAME = "Nama Panggilan";
			TEXT_POINTS = "Skor";
			TEXT_GENERAL_LEADERBOARD = "Umum";
			TEXT_MONTHLY_LEADERBOARD = "Bulanan";
			TEXT_DAILY_LEADERBOARD = "Harian";
			
			TEXT_TERMS_OF_USE = "Ketentuan Penggunaan (EULA)";
			TEXT_PRIVACY = "Kebijakan Privasi";
			TEXT_TERMS_OF_USE_URL = "";
			TEXT_PRIVACY_URL = "https://codethislab.com/code-this-lab-srl-apps-privacy-policy-en/";
			TEXT_PERSONAL_DATA_MANAGEMENT = "Pengelolaan Data Pribadi";
			TEXT_REMOVE_ADS = "Hapus iklan";
			TEXT_SVC_RESTORE = "Memulihkan";
			break;
		}
		case LANG_JA:{
			TEXT_MY_PROFILE = "プロフィール";
			TEXT_CREDITS_URL = "https://www.codethislab.com";
			TEXT_EDIT_PROFILE = "プロフィールを編集する";
			TEXT_LOGOUT = "ログアウト";
			TEXT_LOGIN = "ログイン";
			TEXT_SETTINGS = "設定";
			TEXT_LANGUAGE = "言語 ";
			TEXT_FULLSCREEN_OFF = "フルスクリーンモードオフ";
			TEXT_FULLSCREEN_ON = "フルスクリーンモードオン";
			TEXT_MUSIC_OFF = "オーディオオフ";
			TEXT_MUSIC_ON = "オーディオオン";
			TEXT_SFX_ON = "効果音オン"; 
			TEXT_SFX_OFF = "効果音オフ";
			TEXT_ANIMATION_ON = "アニメーションオン";
			TEXT_ANIMATION_OFF = "アニメーションオフ";
			TEXT_GAME_OPTION = "ゲームオプション";
			TEXT_MAIN_MENU = "メインメニュー";
			TEXT_SB_RESTART = "再スタート";
			TEXT_LEADERBOARD = "リーダーボード";
			TEXT_ONLINE_ROOMS = "オンラインルーム";
			TEXT_REPORT_BUG = "バグを報告する";

			TEXT_STATS = "統計";
			TEXT_ARE_YOU_SURE = "本当によろしいですか？";
			TEXT_MORE_GAMES = "他のゲーム";
			TEXT_MORE_GAMES_SUB = "新しい無料タイトル";
			TEXT_MORE_GAMES_EXP = "もっと ゲーム を プレイしましょうか ？ \n\n[OK]  を クリックして カタログ を ご覧ください。";
			TEXT_CREDITS = "クレジット";
		
			TEXT_REGISTER = "登録";
			TEXT_CLOSE = "閉じる";
			TEXT_EMAIL = "電子メールアドレス";
			TEXT_PWD = "パスワード";
		
			TEXT_SUBMIT = "送信";
			TEXT_NO_LEADERBOARD = "利用可能なリーダーボードはありません";
			TEXT_PLS_LOGIN = "この機能にアクセスするにはログインしてください";
			TEXT_FEATURED_GAMES = "注目のゲーム";
			TEXT_OTHER_GAMES = "他のゲーム";
			TEXT_SEND_EMAIL = "下記までご連絡ください";
			TEXT_RANKING = "ランキング";
			TEXT_WINS = "勝";
			TEXT_DEUCES = "ジュース";
			TEXT_LOSSES = "敗北";
			TEXT_WIN_PERC = "勝利%";
			TEXT_HELP_GAME_RULE = "ゲームのルール";
			
			TEXT_GUEST = "ゲスト";
			
			TEXT_STATS_NO_LOGIN = "進捗 を 保存 する に は ログイン して ください";
			TEXT_PLAY_GUEST = "ゲストとしてプレイする";
			TEXT_LOGIN = "ログイン";
			TEXT_REGISTER = "アカウントを作成する";
			TEXT_FIELDS_NOT_FILLED = "全てのフィールドに入力してください";
			TEXT_MAX_LEN_PWD = "（最大10文字）";
			TEXT_SYS_CONFIRM_PWD = "パスワードの確認";
			TEXT_SYS_REGISTRATION  = "登録パネル";
			TEXT_PWD_NOT_MATCHING = "パスワードが一致しません";
			TEXT_PWD_TOO_SHORT = "パスワードは3文字以上でなければなりません";
			TEXT_PWD_TOO_LONG = "パスワードが長すぎます！ 10文字以内でなければなりません";
			TEXT_EMAIL_NOT_VALID = " 有効なメールアドレスを入力してください";
			TEXT_ERR_USER_ALREADY_REGISTERED = "ユーザー名はすでに登録されています";
			TEXT_ERR_EMAIL_ALREADY_REGISTERED = "メールアドレスはすでに登録されています";
			TEXT_GENERIC_REGISTER_ERR = "登録に失敗しました";
			TEXT_INVALID_PASSWORD = "無効なパスワード";
			TEXT_PWD_FORGOT = "パスワードをお忘れですか";
			TEXT_PWD_RECOVER = "パスワードをリセットするにはメールをご確認ください";
			TEXT_FIND_OPPONENTS = "対戦相手を探しています...";
			TEXT_GENERIC_LOGIN_FAILED = "ログインに失敗しました！";
			TEXT_INVALID_USER = "ニックネームが見つかりません";
			TEXT_YES = "はい";
			TEXT_NO = "いいえ";
			TEXT_DELETE_USER = "ユーザーを削除する";
			
			TEXT_LEADERBOARD = "リーダーボード";
			TEXT_POSITION ="#";
			TEXT_RANK = "ランク";
			TEXT_NICKNAME = "ニックネーム";
			TEXT_POINTS = "スコア";
			TEXT_GENERAL_LEADERBOARD = " 一般";
			TEXT_MONTHLY_LEADERBOARD = "月次";
			TEXT_DAILY_LEADERBOARD = "日々の";
			
			TEXT_TERMS_OF_USE = "利用規約 (EULA)";
			TEXT_PRIVACY = "プライバシー ポリシー";
			TEXT_TERMS_OF_USE_URL = "";
			TEXT_PRIVACY_URL = "https://codethislab.com/code-this-lab-srl-apps-privacy-policy-en/";
			TEXT_PERSONAL_DATA_MANAGEMENT = "個人データ管理";
			TEXT_REMOVE_ADS = "広告を削除する";
			TEXT_SVC_RESTORE = "復元";
			break;
		}
		case LANG_ZH:{
			TEXT_MY_PROFILE = "我的档案";
			TEXT_CREDITS_URL = "https://www.codethislab.com";
			TEXT_EDIT_PROFILE = "编辑档案";
			TEXT_LOGOUT = "登出";
			TEXT_LOGIN = "登录";
			TEXT_SETTINGS = "设置";
			TEXT_LANGUAGE = "语言";
			TEXT_FULLSCREEN_OFF = "关闭全屏模式";
			TEXT_FULLSCREEN_ON = "打开全屏模式";
			TEXT_MUSIC_OFF = "关闭音频";
			TEXT_MUSIC_ON = "打开音频";
			TEXT_SFX_ON = "音效开启"; 
			TEXT_SFX_OFF = "音效关闭";
			TEXT_ANIMATION_ON = "动画开启";
			TEXT_ANIMATION_OFF = "动画关闭";
			TEXT_GAME_OPTION = "游戏选项";
			TEXT_MAIN_MENU = "主菜单";
			TEXT_SB_RESTART = "重新开始";
			TEXT_LEADERBOARD = "排行榜";
			TEXT_ONLINE_ROOMS = "在线房间";
			TEXT_REPORT_BUG = "报告错误";

			TEXT_STATS = "统计数据";
			TEXT_ARE_YOU_SURE = "你确定吗？";
			TEXT_MORE_GAMES = "更多游戏";
			TEXT_MORE_GAMES_SUB = "新的免费标题";
			TEXT_MORE_GAMES_EXP = "你 想 玩 更 多 的 游戏 吗 ？\n\n点击 [OK] 查看 目录。";
			TEXT_CREDITS = " 制作人员";
			
			TEXT_REGISTER = "注册";
			TEXT_CLOSE = "关闭";
			TEXT_EMAIL = "电子邮件地址";
			TEXT_PWD = "密码";
		
			TEXT_SUBMIT = "提交";
			TEXT_NO_LEADERBOARD = "暂无排行榜";
			TEXT_PLS_LOGIN = "请登录以使用此功能";
			TEXT_FEATURED_GAMES = "推荐游戏";
			TEXT_OTHER_GAMES = "其他游戏";
			TEXT_SEND_EMAIL = "请写信给我们";
			TEXT_RANKING = "排名";
			TEXT_WINS = "胜利";
			TEXT_DEUCES = "平局";
			TEXT_LOSSES = "失败";
			TEXT_WIN_PERC = "胜率";
			TEXT_HELP_GAME_RULE = "游戏规则";
			
			TEXT_GUEST = "游客";
			
			TEXT_STATS_NO_LOGIN = "登 录 以 保 存 您 的 进 度";
			TEXT_PLAY_GUEST = "以访客身份玩游戏";
			TEXT_LOGIN = "登入";
			TEXT_REGISTER = "创建账户";
			TEXT_FIELDS_NOT_FILLED = "请填写全部字段";
			TEXT_MAX_LEN_PWD = "（最多 10 个字符）";
			TEXT_SYS_CONFIRM_PWD = "确认密码";
			TEXT_SYS_REGISTRATION  = "注册面板";
			TEXT_PWD_NOT_MATCHING = "密码不匹配";
			TEXT_PWD_TOO_SHORT = "密码必须至少有 3 个字符";
			TEXT_PWD_TOO_LONG = "密码过长！最多 10 个字符";
			TEXT_EMAIL_NOT_VALID = "请输入有效的电子邮件地址";
			TEXT_ERR_USER_ALREADY_REGISTERED = "用户名已注册";
			TEXT_ERR_EMAIL_ALREADY_REGISTERED = "邮箱已注册";
			TEXT_GENERIC_REGISTER_ERR = "注册失败";
			TEXT_INVALID_PASSWORD = "密码无效";
			TEXT_PWD_FORGOT = "忘记密码";
			TEXT_PWD_RECOVER = "检查您的电子邮件以重置密码";
			TEXT_FIND_OPPONENTS = "寻找对手...";
			TEXT_GENERIC_LOGIN_FAILED = "登录失败！";
			TEXT_INVALID_USER = "未找到昵称";
			TEXT_YES = "是的";
			TEXT_NO = "不";
			TEXT_DELETE_USER = "删除用户";
			
			TEXT_LEADERBOARD = "排行榜";
			TEXT_POSITION = "#";
			TEXT_RANK = "等级";
			TEXT_NICKNAME = "昵称";
			TEXT_POINTS = "分数";
			TEXT_GENERAL_LEADERBOARD = "总体";
			TEXT_MONTHLY_LEADERBOARD = "月度";
			TEXT_DAILY_LEADERBOARD = "日常";
			
			TEXT_TERMS_OF_USE = "使用条款（最终用户许可协议）";
			TEXT_PRIVACY = "隐私政策";
			TEXT_TERMS_OF_USE_URL = "";
			TEXT_PRIVACY_URL = "https://codethislab.com/code-this-lab-srl-apps-privacy-policy-en/";
			TEXT_PERSONAL_DATA_MANAGEMENT = "个人数据管理";
			TEXT_REMOVE_ADS = "移除广告";
			TEXT_SVC_RESTORE = "恢复";
			break;
		}
	}
}